### ISSUE TITLE
please tell us what does it take to get this outta beta via milestones

### ISSUE THREAD

**Issue by cordoval** [phiamo/MopaBootstrapBundle#1000]

**Comment by isometriks** [comment]
I'll try to work on this when I get a chance. I've discussed with @phiamo about how to do this and I think we're just going to make master 3.0, and then the new branch I was starting be 3.2. The biggest problem we need to address is abstracting different versions of bootstrap:

- https://github.com/phiamo/MopaBootstrapBundle/pull/1003
- https://github.com/phiamo/MopaBootstrapBundle/pull/992
- https://github.com/phiamo/MopaBootstrapBundle/pull/983

etc.. I don't like having all these base SASS/LESS files that people just include as there are differences between 3.0/3.2. If I merge one of these PRs then I'll have new PRs with people saying it broke older versions. 

We were thinking about going about it like this: https://github.com/phiamo/MopaBootstrapBundle/tree/v3.0-dev/Resources/config/assetic

And having people include the correct config file for what bootstrap version you're using. Then always using `@bootstrap_css` in assetic so we don't need multiple templates. (Which I'm still kind of against having lots of base templates here as any changes to them can cause BC breaks in any number of projects - Unless the templates are VERY basic)

I will probably merge some of those commits here to allow config imports for setting up the assets and still leave the old way, and remove the old way in 3.2 branch (3.0-dev now) along with some other "features" that I think make this bundle a bit bloated and hard to maintain.

**Comment by phiamo** [comment]
@cordoval we were discussing and having these probs throughout the last year, would be best to not have strong deps to the bootstrap version, but as we saw there is a lot of things to consider. 
If you have any further ideas on howto get that quickly into the right direction lets discuss them. i see the urgend point of getting another stable version out

**Comment by phiamo** [comment]
I think we should now give all these merges a bit time to get tested through the community, but i think we could release a RC1, @isometriks what do you think? most of these efforts were afforded by you!

**Comment by phiamo** [comment]
@isometriks @cordoval since the most things are actually working and recent work on travis by @Soullivaneuh as well as a lot of improvements were made, i would like to release a RC1 soon.

**Comment by Soullivaneuh** [comment]
@phiamo I'm was just wondering the same asking for 3.0 release.

What else should be made before it? Could I help on any plan?

Regards

**Comment by cordoval** [comment]
@phiamo nobody is holding you, just yourself :+1: go for it and release not RC but a release! :sheep: :it:

**Comment by MisatoTremor** [comment]
:+1:

**Comment by cordoval** [comment]
why the closing?

**Comment by isometriks** [comment]
We have the milestone for 3.0 and there's nothing left to do in this issue as far as I can tell so I'm closing it to keep only issues that are unresolved. The point of the milestone is to release 3.0 so this seems redundant.

**Comment by isometriks** [comment]
If you have any other suggestions for 3.0 feel free to make another issue with that problem and we can add it to the milestone

**Comment by cordoval** [comment]
is good to close, let's tag 3.0 asap, thanks for the work
