### ISSUE TITLE
please move wiki 2 only pages to proper documentation into a bundle

### ISSUE THREAD

**Issue by cordoval** [phiamo/MopaBootstrapBundle#1001]

**Comment by phiamo** [comment]
@cordoval dont get it, can you explain a bit further which actions to take

**Comment by cordoval** [comment]
there are just a couple of  pages on the wiki on github of this repository. The idea would be to move those to the versioned code documentation for this bundle.

**Comment by phiamo** [comment]
@cordoval ok yes, the branches page was out of date and is in a seperate file: https://github.com/phiamo/MopaBootstrapBundle/blob/master/BRANCHES.md
the less info in https://github.com/phiamo/MopaBootstrapBundle/wiki is as far as i can see completely inside the different pages of the docs

**Comment by cordoval** [comment]
Let's remove this then imean the wiki

**Comment by phiamo** [comment]
done
