### ISSUE TITLE
Nested collection is broken

### ISSUE THREAD

**Issue by piotrantosik** [phiamo/MopaBootstrapBundle#1014]
Commit 89344f914155a7bcf805cf5354bd3ad208a94f11 broke prototype replacement in nested collection.

**Comment by phiamo** [comment]
@molchanoviv @piotrantosik  do you have time to look into this soon?

**Comment by phiamo** [comment]
@piotrantosik can you create a example for sandbox with a nested collection?

**Comment by molchanoviv** [comment]
@piotrantosik Can you describe in details what is wrong with it?

**Comment by piotrantosik** [comment]
repo url: https://github.com/piotrantosik/mopatest
screen: 
![image](https://cloud.githubusercontent.com/assets/154553/5754983/a19d7416-9c9f-11e4-8dd5-15317255d91d.png)

when using old regexp pattern pattern is replacement correctly

**Comment by molchanoviv** [comment]
Ok. I'll try to figure the problem out and fix it this weekends.

**Comment by molchanoviv** [comment]
Yeah. I found a problem. RegExp should be like this

    "((\"|&quot;|'|&#039;)((?!(\"|&quot;|'|&#039;|" + prototype_name + ")).)+?)(" + prototype_name + ")"

**Comment by piotrantosik** [comment]
not working, is a strange, (random?) problem
when i add only first nested level form is work correctly:

![image](https://cloud.githubusercontent.com/assets/154553/5755569/608f5d16-9ca6-11e4-94a5-6c6be2ae1d5b.png)

but when i add form2 and on form2 another nested form and next other form2 prototype is not replacement.

![image](https://cloud.githubusercontent.com/assets/154553/5755640/34c0e8ac-9ca7-11e4-86db-b0c0fd12a7af.png)

**Comment by phiamo** [comment]
@piotrantosik can you check #1027 if it fixes your problem?

**Comment by piotrantosik** [comment]
@phiamo not fixed, maybe this screencast can be helpful, ping @molchanoviv 
http://youtu.be/pxYOLVKKlAw
