### ISSUE TITLE
Fix travis for SF >=2.7

### ISSUE THREAD

**Issue by phiamo** [phiamo/MopaBootstrapBundle#1024]
Since tracis is currently not liking our code for sf >=2.7 since some methods are then deprecated 
we need to find a way around this.
see discussion here https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/commit/f227d42640d5e8bee64ec3ecbcefb0068cd32886
and new component here
https://github.com/symfony/symfony/pull/13398

**Comment by isometriks** [comment]
We should get this back up running again and probably release a 3.0 soon, haven't had any big issues lately so let's just get it over with!

**Comment by Soullivaneuh** [comment]
@phiamo Not sure, but I think could be closed also.

Now all is green on Travis, even if SF 2.7/2.8/3.0 allowed failures! ;-)

**Comment by phiamo** [comment]
jau thanks!
