### ISSUE TITLE
Initializr feature should be moved to another bundle

### ISSUE THREAD

**Issue by LouTerrailloune** [phiamo/MopaBootstrapBundle#1025]
I don't understand why this is included in this bundle (which is already big).

**Comment by isometriks** [comment]
Agreed, I've already removed it from the next release. Once we release 3.0 that will stay as a 3.0 branch and dev-master or 3.2-dev or something will have this removed. I don't think we plan to remove this for the 3.0 release though, or any other BC breaks for that matter.
