### ISSUE TITLE
Remove number lables from collection subform

### ISSUE THREAD

**Issue by alexdrupal** [phiamo/MopaBootstrapBundle#1031]
Hi Folks

I have a subform of collection type. How can I remove numbers from it?
![collection](https://cloud.githubusercontent.com/assets/38625/6082079/675801f8-ae2f-11e4-877f-ac7e57331cb7.png)

**Comment by grimmlink** [comment]
```
'options' => array(
    'label_render' => false,
)
```

in your collection formtype

**Comment by alexdrupal** [comment]
Thank you! Thank you! Thank you!
Can't believe I spent so much time on this.

**Comment by phiamo** [comment]
:-) thanks @grimmlink
