### ISSUE TITLE
widget_remove_btn does not work in collection (but it works in config.yml).

### ISSUE THREAD

**Issue by 5zymon** [phiamo/MopaBootstrapBundle#1033]
Hello,

I am using  "mopa/bootstrap-bundle": "3.*@dev" version of MopaBootstrapBundle, and I am having problems trying to override remove button settings in collection.  In my collection I am trying to do this

                    'widget_remove_btn' => array(
                        'label' => 'Remove Filter',
                        'attr' => array(
                            'class' => 'btn btn-red'
                        )
                    ),
                    'widget_add_btn' => array(
                        'label' => 'Add Filter',
                        'icon' => 'plus-sign',
                        'attr' => array(
                            'class' => 'btn btn-primary btn-add-filter'
                        )
                    ),

And the add button settings work fine, but the remove button is still labeled as "remove_item" and none of the settings are pplied. If I try to override remove button settings in config.yml within mopa_bootstrap section they ARE applied, so it works.

**Comment by Misiur** [comment]
Remove has to be inside "options" attribute, as it applies to collection items, not whole collection. That's weird, but makes sense.

**Comment by phiamo** [comment]
so we can close this.
