### ISSUE TITLE
[DX] Simplify customization of collection rendering

### ISSUE THREAD

**Issue by daFish** [phiamo/MopaBootstrapBundle#1034]
I'm currently trying to customize the rendering of a collection to be able to display the collection entries in a table rather than divs.

My approach was as following:
- create a new form theme for this special purpose.
- override the following blocks to modify them for my needs `collection_widget`, `form_row`, `widget_form_group_start`, `widget_form_group_end`
- override the rendering of the collection entry widget

This is working to the extend where I want to remove an entry from the collection. The JS cannot find the row to be deleted: `row not contained in collection`.
Another issue that came up was already having items in my collection. These need to be displayed as well which isn't the case right now.

I was wondering if there is a better, easier and more intuitive approach? Either by modularize the blocks more or by writing some kind of cookbook which deals with this issues.

**Comment by daFish** [comment]
Added another note: `Another issue that came up was already having items in my collection. These need to be displayed as well which isn't the case right now.`

**Comment by daFish** [comment]
@isometriks @phiamo @jdespatis Any input on this?

**Comment by phiamo** [comment]
@daFish sry didnt get github notifications for a while :/ 
is this problem also there when not overriding the default behavios? probably for the row not found you might need to adapt the selectors used in the js

**Comment by daFish** [comment]
@phiamo 
When I use the default behavior it works as expected. So I guessed that there might be something missing.

Is it already possible to do this for the JS? If so, that would be great.

**Comment by phiamo** [comment]
@daFish as far as i see the default behaviour would be to search the closest .collection-item to the button and remove this if its in the collection.
so have a look on the original markup,  and https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/public/js/mopabootstrap-collection.js you need to have a similar structure setup, so the js initializes the collections correctly, probably you could create a pr to the sandbox to play around, would be best to have a theme and use this for another collection in the collections page http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/collections the trick should be, that you just need the correct markup.

**Comment by phiamo** [comment]
ping @daFish
