### ISSUE TITLE
mopa:bootstrap:symlink:sass uses wrong pathToTwitterBootstrapSass

### ISSUE THREAD

**Issue by grimmlink** [phiamo/MopaBootstrapBundle#1037]
Hi,

I tried many times to use the command line to generate the link between bootstrap bundle and bootstrap-sass, and everytime the create symlink is wrong.

Example:

```
pathToTwitterBootstrapSass = '../../../../../../../twbs/bootstrap-sass'
pathToMopaBootstrapBundle = 'vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/bootstrap-sass'
```

the symlink created : 
`vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/bootstrap-sass -> vendor/twbs/bootstrap-sass`
which is wrong

That's from [BaseBootstrapSymlinkCommand](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Command/BaseBootstrapSymlinkCommand.php#L205)

The `$symlinkTarget` is overwritten by the resolved path, `../../../../../../../twbs/bootstrap-sass` becomes `vendor/twbs/bootstrap-sass`

**Comment by henrypenny** [comment]
I encountered this problem a long time ago, and I had to write a compiler pass to correct this.
I recently upgraded the project to symfony ~2.6 and it seemed I still required the compiler pass.
I don't know if this is the correct solution, but it did work in my project.

Compiler pass:

    <?php
    namespace <Bundle>\DependencyInjection\Compiler;

    use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
    use Symfony\Component\DependencyInjection\ContainerBuilder;

    class SassPass implements CompilerPassInterface {

        public function process(ContainerBuilder $container)
        {
            if ($container->hasDefinition('assetic.filter.sass')) {
                $container->getDefinition('assetic.filter.sass')->addMethodCall('addLoadPath',
                    array("%kernel.root_dir%/../vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass/")
                );
            }
            if ($container->hasDefinition('assetic.filter.scss')) {
                $container->getDefinition('assetic.filter.scss')->addMethodCall('addLoadPath',
                    array("%kernel.root_dir%/../vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass/")
                );
            }
        }
    }

Bundle:

    <?php
    
    namespace <Bundle>;
    
    use <Bundle>\DependencyInjection\Compiler\SassPass;
    use Symfony\Component\DependencyInjection\ContainerBuilder;
    use Symfony\Component\HttpKernel\Bundle\Bundle;
    
    class <Bundle> extends Bundle
    {
        ....
        public function build(ContainerBuilder $container)
        {
            $container->addCompilerPass(new SassPass());
            ....
        }
        ...
    }

**Comment by phiamo** [comment]
probably we could include this by default?

**Comment by henrypenny** [comment]
I was never certain whether the original problem was a real bug or some misconfiguration on my part.

**Comment by toby-griffiths** [comment]
I've had this problem just this week when deploying the same way I always have.  I'm not sure what's changed.
I did work out, however, that if you install your assets using the --symlink switch (`app/console assets:install --symlink`) it appears to work fine.
Perhaps this helps work things out?
