### ISSUE TITLE
Form tabs. Change tab with error field after validation

### ISSUE THREAD

**Issue by WarGot-by** [phiamo/MopaBootstrapBundle#1038]
Hi all. I need help -)
I use this example for create tabs http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/tabs
Open the second tab. Then click "Save changes", appear error fields. Somewhere at the top of the page. How to make to switch tabs. On the one where the error occurred.

**Comment by isometriks** [comment]
Are you looking to do this front-end with HTML5 validation? I actually went through this same thing, here ya go: http://isometriks.com/highlight-twitter-bootstrap-error-in-forms-with-ta

The jQuery can probably be simplified a bit but you can get the idea.

**Comment by phiamo** [comment]
so can we close this ?
