### ISSUE TITLE
assetic:dump prints errors related to MopaBootstrapBundle

### ISSUE THREAD

**Issue by emil-nasso** [phiamo/MopaBootstrapBundle#1041]
I get the following error when dumping assets, `php app/console assetic:dump`. If i run the command twice, the errors does not appear on the second run. If i re-run composer install (or redeploy) the error reapper when dumping again.

```
[2015-03-03 16:01:55] assetic.ERROR: The template "MopaBootstrapBundle::base_sass_3.2.html.twig" contains an error: Unable to find file "@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js".  
[2015-03-03 16:01:55] assetic.ERROR: The template "MopaBootstrapBundle:Form:formflow_stepList.html.twig" contains an error: The filter "craue_addDynamicStepNavigationParameter" does not exist in "MopaBootstrapBundle:Form:formflow_stepList.html.twig" at line 7  
[2015-03-03 16:01:55] assetic.ERROR: The template "MopaBootstrapBundle::base_sass.html.twig" contains an error: Unable to find file "@MopaBootstrapBundle/Resources/public/bootstrap-sass/vendor/assets/javascripts/bootstrap/tooltip.js".  
```

This is how the scripts in my composer file looks.

```
"post-install-cmd": [
      "Mopa\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::postInstallSymlinkTwitterBootstrap",
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
    ],
    "production-deploy": [
      "php symfony/app/console assetic:dump; php symfony/app/console assetic:dump;"
    ]
```

I am using less in my application, not sass.

**Comment by isometriks** [comment]
Can you post your configuration for assetic? It is probably trying to dump all the stylesheets tags in MopaBootstrap when you should just be extending these templates and adding your local bundle

**Comment by emil-nasso** [comment]
Ah. Okay.

Here it is:
´´´
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "MopaBootstrapBundle"]
    read_from:      "%kernel.root_dir%/../../htdocs/symfony"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
          node: /usr/bin/node
          node_paths: [/opt/lessc/lib, /usr/lib/node_modules, /usr/local/lib/node_modules]
          apply_to: "\.less$"

```

**Comment by isometriks** [comment]
Yeah, remove MopaBootstrapBundle from the `bundles` list. If you extend one of the templates from this bundle in your /app folder then it should automatically dump the assets because you're extending the template. If you have another local bundle like AppBundle or something, you can add that instead. The way you have it now assetic is going to look through all of MopaBootstrap for `{% stylesheet %}` tags and will attempt to dump them (Dumping SASS/LESS etc) which you don't want.

**Comment by Tjeerd** [comment]
I've got the same issue, removing `MopaBootstrapBundle` from the `bundles` option doesn't work either because then an error is shown which tells you to add the bundle to the `bundles` list again ;)
