### ISSUE TITLE
FormActionsType not documented

### ISSUE THREAD

**Issue by toby-griffiths** [phiamo/MopaBootstrapBundle#1047]
I've just found the FormActionsType class while debugging a form.

I couldn't find anything in the documentation about this, and ended up implementing my own 'buttons' type.

Raising this issue, to flag the need to add this to the documentation on http://bootstrap.mohrenweiserpartner.de/mopa.

I followed the 'Fork me' link on the site, but it's forking the bundle, not the demo site.

If you want to let me know the best way to add this, I'll have a go when I have a moment?

**Comment by phiamo** [comment]
Hi @toby-griffiths,
have a look in here https://github.com/phiamo/MopaBootstrapSandboxBundle this drives the demo site.

**Comment by phiamo** [comment]
@toby-griffiths is this solved for you, or do you think we should add more doc somewhere, and could you take care of it?

**Comment by toby-griffiths** [comment]
@phiamo Thanks for getting back to me.  I still couldn't find reference to the FormActionsType class anywhere in the Sandbox site code, either

**Comment by isometriks** [comment]
Will try to add some docs for this soon, but here's another comment I wrote about how to use:

    $builder->add('actions', 'form_actions', array(
        'buttons' => array(
            'save' => ['type' => 'submit', 'options' => ['label' => 'button.save']],
            'cancel' => ['type' => 'button', 'options' => ['label' => 'button.cancel']],
        ),
        'button_offset' => 'col-md-offset-3',
    ));

**Comment by phiamo** [comment]
@isometriks very nice!

**Comment by toby-griffiths** [comment]
Thanks for the info.  Very helpful.  Hoping when this project's calmed down I'll have time to actually put in some work to help you out.

**Comment by phiamo** [comment]
so i assume we can close this? @toby-griffiths @isometriks

**Comment by toby-griffiths** [comment]
I'm happy with that, as it's been added to the documentation issue.
