### ISSUE TITLE
help_block is not displayed

### ISSUE THREAD

**Issue by irisSchaffer** [phiamo/MopaBootstrapBundle#1051]
`help_block` is not displayed on the master branch, because the `if`-statement of the `form_message`-block in [`Resources/views/Form/fields.html`](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/Form/fields.html.twig)  does not work:

    {% block form_message %}
    {% spaceless %}
        {{ form_errors(form) }}
        {# certain cases require to have the help somewhere else in dom, is there any better place or way to handle this? #}
        {% if not(widget_checkbox_label == 'label' and help_block) %}
        {{ block('form_help') }}
        {% endif %}
    {% endspaceless %}
    {% endblock form_message %}

Firstly, the `not` is also around the `help_label`, which means, if there is a help label, it will not get inside the if.
Secondly, checking `widget_checkbox_label == 'label'` is not good enough to see whether the current form is a checkbox and has `widget_checkbox_label` set to `"label"`: If the option is set globally (so you don't have to specify it over and over again on each checkbox), every form field will have the option `widget_checkbox_label` set to the default, not only checkbox fields.

A solution for the first problem would be to simply change the if statement to be:

    {% if widget_checkbox_label != 'label' and help_block %}

or simply

    {% if widget_checkbox_label != 'label' %}

(as the `help_block` is checked in the `form_help`-block anyway.)

I am not entirely sure how to handle the second problem, but maybe the option should only be added to checkboxes in the first place, or a more clever way of determining whether we are currently working with a checkbox has to be found.

**Comment by isometriks** [comment]
Hmm yeah, https://github.com/phiamo/MopaBootstrapBundle/commit/c3e88905e9b5a0404d3dbd53122d54081ba6d51c causes this. I had noticed my help blocks missing too and hadn't looked into it. I'll figure something out tomorrow

**Comment by irisSchaffer** [comment]
Cheers!

**Comment by isometriks** [comment]
https://github.com/phiamo/MopaBootstrapBundle/pull/1053/files should do it, or looks to work for me. Want to try that out quick?

**Comment by isometriks** [comment]
@phiamo I think this still keeps what you wanted. Putting the help_block for checkbox = label into the label itself, and for widget / both putting it under the lable, correct?

**Comment by irisSchaffer** [comment]
@isometriks looks fine to me, my `help_block`s are working as expected again.
