### ISSUE TITLE
Font awesome version

### ISSUE THREAD

**Issue by jackbentley** [phiamo/MopaBootstrapBundle#1055]
The font awesome icons provided by mopa are not up to date. Its missing icons such as `user-add`.

Ideally, mopa should have a dependency in composer on the font-awesome repo - https://github.com/FortAwesome/Font-Awesome

This would allow people to choose their own version at will.

**Comment by Soullivaneuh** [comment]
@jackbentley How is font-awesome provided actually? On which subpackage?

**Comment by jackbentley** [comment]
They're located in mopa in sub-directories withing MopaBootstrapBundle/Resources/public/.

**Comment by Soullivaneuh** [comment]
ping @phiamo what do you think? Could be indeed better to add it as a dependencies.

Or just a suggestion because some developers use bower/npm for assets dependencies.

**Comment by phiamo** [comment]
yeah in future that makes sense, but for 3.0 release i think we need to stick to BC compat and have them there, also some of these are especially modified for this bundle needs ...

**Comment by Soullivaneuh** [comment]
Ok.

@jackbentley Just for information, I use this bundle with font-awesome from bower deps, cause no problem. Maybe you should include your own. :+1:

**Comment by isometriks** [comment]
Yeah I had wanted to look into the SpBowerBundle eventually but for noobs it's just another dependency to require so it's hard.. but at the same time I hate having other libraries stored in our repo.

**Comment by phiamo** [comment]
Yes  :+1: a documentation or good howto/stackoverflow dontknow entry woul be awesome, and then getting rid of external things

**Comment by phiamo** [comment]
so i close this
