### ISSUE TITLE
menu: option 'dropdown' overwrites classes on this menu item

### ISSUE THREAD

**Issue by tulanowski** [phiamo/MopaBootstrapBundle#1058]
When you set some class on element item and you add some children to this element, then this class is overwritten by 'dropdown' (and optionally 'caret') class. In my opinion 'dropdown' class should be appended to previously set classes.

**Comment by phiamo** [comment]
can you isolate where the problem comes from?

**Comment by tulanowski** [comment]
Yes, it happens here:
https://github.com/phiamo/MopaBootstrapBundle/blob/master/Menu/Factory/MenuDecorator.php#L61

Something like this:
```
$item
    ...
    ->setAttribute('class', 'dropdown ' . $item->getAttribute('class'))
```
should fix the problem.

I think that this problems also affects other options like 'pills', 'stacked', 'list-group', etc. Most of those options overwrite 'class' either with setAttribute() or setChildrenAttribute().

**Comment by phiamo** [comment]
can you create a pr for this

**Comment by phiamo** [comment]
so this could be closed
