### ISSUE TITLE
wrong boostrap-sass path

### ISSUE THREAD

**Issue by hlorridi** [phiamo/MopaBootstrapBundle#1070]
*CRITICAL - Uncaught PHP Exception Twig_Error_Syntax: "An exception has been thrown during the compilation of a template ("Unable to find file "@MopaBootstrapBundle/Resources/public/bootstrap-sass/vendor/assets/javascripts/bootstrap/tooltip.js".")*

Real Path is
*@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js*

**Comment by isometriks** [comment]
https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/usage/1-base-templates.md#templates

Does using the 3.2 sass template work? Bootstrap has 2 different paths for < 3.2 and 3.2+, If so I can reopen but I think this is solved.

**Comment by hlorridi** [comment]
my bad, sorry
