### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by isometriks** [phiamo/MopaBootstrapBundle#1072]
- [ ] Clean up other bundles docs
  -  [ ] KnpMenuBundle - Should use `mopa_bootstrap_menu` to use our templates
- [ ] Form Extension - We should have a doc in doc/form for almost every form extension and how to use it.
  - [ ] https://github.com/phiamo/MopaBootstrapBundle/issues/1047 FormActionsType
- [ ] Branches - Do we still want to keep documentation and active branches for 2.3 (README.md)? Or change main documentation to just say use bootstrap 3 and our 3.0 branch?
- [ ] Do we need these?
  - [ ] https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/misc/including-bootstrap.md
  - [ ] https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/misc/windows-tips.md
- [ ] https://github.com/phiamo/MopaBootstrapBundle/tree/master/Resources/doc/usage 
  - [ ] Split up usage documentation into using `stylesheets` etc, and then how to use base templates. 
- [ ] [Documentation for flashes](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/flash.html.twig) - I would like to add that Twig can use named parameters so it's possible to do `flash('type', 'message', close=true, domain='FOSUserBundle')` instead of passing null to every parameter
- [ ] Update [form testing](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/misc/testing-forms.md) to show how to use the XPath tests instead of doing unit tests which is really hard to do on this bundle because of all the dependent form types.

**Comment by phiamo** [comment]
is this still in same state or havent there been several improvements?

**Comment by isometriks** [comment]
Pretty much the same state. I just reorganized the docs a little, we still need to clean it up. Especially noting about the sass3.2 problem cause we still get issues about it

**Comment by jonny827** [comment]
@isometriks @phiamo 

Would you like some assistance on this one? 

I myself am having some issues trying to use bootstrap "out of the box" with the bundle and maybe I could help with common hurdles section (from a first-timers perspective) and have some input on the components I have implemented so far.

**Comment by phiamo** [comment]
@jonny827 of course feel free to open a PR for discussing howto do that effectivly

**Comment by jonny827** [comment]
@phiamo Unfortunately I have an active PR that needs to be merged already so I am unable to open a second one. 

This is one reason I believe we should migrate MopaBootstrap Documentation into its own repository especially is the library ever gets split from the bundle like discussed in Issue #953.

The second reason is that the documentation can contain a great deal of examples and use cases that is unnecessary important into a bundle that will be used in production.

The third it would provider better separation for branch versioning which is tied to library versioning.versus trying to maintain that in text within /resources/doc. 

The fourth reason is that it keeps a great deal of the issues with docs and other "how-to" related outside the actual functional issues and PR discussion. When someone submits within the library or bundle they will also submit a PR if any documentation needs updating.  

The fifth reason is the most important......The documentation removed from the bundle repository allows the library/bundle split to be more of an easy transition and the documentation could also then have sections for Symfony (and other integrations) or just using the core MOPA library in a raw php project like you would use KNP Menu.  The power of Mopa would draw a ton more developers with better docs, and an exponential amount of more developers if we opened it up to more than just the Symfony community. The presentation layer is a very important aspect and the "thorn in most developers sides" an accessible decoupled library with integration to the worlds popular php frameworks would be nice  ----  laravel, silex, symfony, etc...

**Comment by phiamo** [comment]
@jonny827 
thanks for explanaition 
for the moment the sandbox contains anyways most of the living examples, maybe thats a good point to start https://github.com/phiamo/MopaBootstrapSandboxBundle

**Comment by jonny827** [comment]
I have begun an  Issue in the Sandbox Repository to discuss [MopaBoostrap Documentation / Future of MopaBootStrap #47](https://github.com/phiamo/MopaBootstrapSandboxBundle/issues/47) .   Can we move this discussion there?  I think it we discuss the future of MopaBoostrap then we can then decided where the Documentation/Bundle/Sandbox/(and Potentially Library) all need to end at up.
