### ISSUE TITLE
close_tag not working

### ISSUE THREAD

**Issue by d-a-gerashenko** [phiamo/MopaBootstrapBundle#1083]
https://github.com/phiamo/MopaBootstrapBundle/blob/a5573423b7d029d65bf85e3eba336d5d85d695f1/Resources/views/flash.html.twig
Line 17 always true.
Replace with: close_tag == 'true'

**Comment by phiamo** [comment]
Can you please create a PR
Am 23.06.2015 09:47 schrieb "Dmitriy Gerashenko" <notifications@github.com>:

**Comment by d-a-gerashenko** [comment]
https://github.com/phiamo/MopaBootstrapBundle/blob/a5573423b7d029d65bf85e3eba336d5d85d695f1/Resources/views/flash.html.twig
Line 17

**Comment by d-a-gerashenko** [comment]
Done  #1087
