### ISSUE TITLE
Less installation

### ISSUE THREAD

**Issue by womanly** [phiamo/MopaBootstrapBundle#1089]
I am having problems installing LESS in my Windows 7 OS. I have already installed node.js, and now I don't know what else I have to do. Please, could anyone tell me the steps I must follow? Thanks in advanced.

**Comment by phiamo** [comment]
sry never did this on windows, probably you can identify your steps based on https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/install/2-less-installation.md
