### ISSUE TITLE
How do I install the full glyphicons font?

### ISSUE THREAD

**Issue by toby-griffiths** [phiamo/MopaBootstrapBundle#1102]
I've purchased the full Glyphicons set & would like to use them with the this bundle.  Is anyone able to advise the simplest way to do this?

Thanks in advance,

Toby

**Comment by isometriks** [comment]
Place in your AppBundle/Resources/public and then link with /bundles/app/glyphicons/... with assetic or whatever you use. Glyphicons are default icons so you can just use twig in your templates: `{{ icon('pencil') }}` etc.
