### ISSUE TITLE
Change `extends` to `use` in form fields template

### ISSUE THREAD

**Issue by c1tru55** [phiamo/MopaBootstrapBundle#1109]
'MopaBootstrapBundle:Form:fields.html.twig' should `use` 'form_div_layout.html.twig' template instead of `extending` it. See how it is implemented in Symfony: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig#L1

Otherwise 'MopaBootstrapBundle:Form:fields.html.twig' template cannot be `used` in other templates in its turn. Also if we have 2 templates which extend same 'MopaBootstrapBundle:Form:fields.html.twig' template, but override **different** blocks - overridden blocks from **first** of these templates will be **ignored** (since these blocks can be also found in last template with higher priority via inheritance).

**Comment by MisatoTremor** [comment]
See PR #1104

**Comment by c1tru55** [comment]
@MisatoTremor  :+1:
