### ISSUE TITLE
Change static_text to be a form type

### ISSUE THREAD

**Issue by isometriks** [phiamo/MopaBootstrapBundle#1111]
Change `static_text` extension to be a form type that extends the `hidden` form type so it passes along data if needed. It should output the hidden element along with the <p> tag for static text in the form.

**Comment by phiamo** [comment]
@isometriks is this connected to https://github.com/phiamo/MopaBootstrapBundle/pull/1132 ?

**Comment by isometriks** [comment]
Yes it is. I think it should be done through a type not through options and override the whole form type. It also doesn't pass any data if that's actually needed by people

**Comment by peshi** [comment]
What kind of data do you want to pass for static text?

**Comment by isometriks** [comment]
Sorry I thought you were the one that wanted to actually have it come from the data and possible even pass it. I was thinking maybe a scenario where you want hidden data that can't be edited but you can also read what it is. Maybe for somebody filling something else out that isn't an entity yet?

```php
$builder
    ->add('email', 'static_text')
    ->add('phone', 'text')
;

$form = $builder->getForm();
$form->setData(array(
    'email' => 'me@email.com',
));
```

That way the static text would come from the data instead of having to read the data yourself and then set it as a form option.

**Comment by peshi** [comment]
Ah, I understand - an example use case was nice to see. That could be usefull :+1:

**Comment by peshi** [comment]
I like the idea and can already see a few places where I could use this.

**Comment by isometriks** [comment]
Yeah it would be nice in some admin gui that wants to show the value but not let it get changed. In that case mapped false would be fine even if somebody inspected element and changed the hidden field as it wouldn't take the value regardless. You wouldn't need a full custom template to display your form and only have one thing be just a value. I could imagine maybe the ID of the entity being static text so the first row in your form shows the ID but doesn't let you edit it.

**Comment by peshi** [comment]
In the StaticTextExtension i used http://symfony.com/doc/current/reference/forms/types/text.html#disabled
But I didn't actually test to inspect and remove a disabled tag to push a different value, but I guess it would swallow the value and update the entity/document.

So, yes that would be neat if this could be done as described in your comment.
