### ISSUE TITLE
[feature request] Accordion Menu

### ISSUE THREAD

**Issue by quazardous** [phiamo/MopaBootstrapBundle#1121]
Hi,

I would love an accordion menu like this 

http://bootsnipp.com/snippets/featured/accordion-menu

Maybe it is already doable ?

**Comment by isometriks** [comment]
Do you want to create this from a knp menu? If so you can pass a custom template to either the `mopa_bootstrap_menu` or `knp_menu_render` 

`{{ mopa_bootstrap_menu('mymenu', {'template': 'AcmeBundle:Menu:accordian.html.twig'}) }}`

You'll want to go look at knp's menu template so you'll know what blocks to override.

**Comment by quazardous** [comment]
yes something like this ... but I'm still looking for a nice snippet because the one I ve found has (evil) table...
If you guys have some ideas or snippets...

**Comment by isometriks** [comment]
I would just use this: http://getbootstrap.com/javascript/#collapse-example-accordion in conjunction with this: http://getbootstrap.com/components/#panels-list-group

It's already built into bootstrap. Just use their accordion with panel list groups.

**Comment by phiamo** [comment]
i assume this is done .. thanks @isometriks
