### ISSUE TITLE
Form - Type+Extension

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#1122]
Reminder to fix form types and extensions up to 2.8 before dropping BC.
https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md

**Comment by isometriks** [comment]
https://github.com/phiamo/MopaBootstrapBundle/pull/1117

Just posting to link these, I need to look into it a little more but I think the PR looks good.

**Comment by peshi** [comment]
@isometriks thanks, I missed this PR while browsing. I'll comment in PR.

**Comment by phiamo** [comment]
thanks!
