### ISSUE TITLE
Error in path

### ISSUE THREAD

**Issue by bnd170** [phiamo/MopaBootstrapBundle#1123]
You have an error in the dev-master branch.

On this file:
/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass/mopabootstrapbundle.scss

Line 26:
@import "../bootstrap-sass/assets/stylesheets/bootstrap/bootstrap";

Fix it with this:
@import "../bootstrap-sass/assets/stylesheets/bootstrap.scss";

**Comment by isometriks** [comment]
Use mopabootstrapbundle-3.2.scss, they changed the paths in 3.2 but we wanted to still support older versions if people were still using it.

**Comment by bnd170** [comment]
Okey, another question. How can i add FontAwesome using mopabootstrapbundle-3.2?

**Comment by phiamo** [comment]
i never used sass but there is something here: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/public/sass/bootstrap-fontawesome.scss
