### ISSUE TITLE
Post-cmd-cmd creates a wrongly bootstrap-sass folder in web

### ISSUE THREAD

**Issue by bnd170** [phiamo/MopaBootstrapBundle#1124]
Don't knwo why but after i install JMSi18nRoutingBundle, it works wrongly :/

I need some help to fix it.

![Image](http://i.imgur.com/vZFKV4x.png)
![Image](http://i.imgur.com/zyKwrR0.png)

**Comment by phiamo** [comment]
have you tried removing it and then retring?

**Comment by bnd170** [comment]
Yes, but doesnt work

2015-11-26 20:18 GMT+01:00 Philipp A. Mohrenweiser <notifications@github.com
