### ISSUE TITLE
Deprecation notice Twig_ExtensionInterface::initRuntime()

### ISSUE THREAD

**Issue by stephanvierkant** [phiamo/MopaBootstrapBundle#1125]
http://twig.sensiolabs.org/doc/deprecated.html:
> As of Twig 1.23, the Twig_ExtensionInterface::initRuntime() method is deprecated. You have two options to avoid the deprecation notice: if you implement this method to store the environment for your custom filters, functions, or tests, use the needs_environment option instead; if you have more complex needs, explicitly implement Twig_Extension_InitRuntimeInterface (not recommended).

Defining the initRuntime() method in the "mopa_bootstrap_icon" extension is deprecated. Use the `needs_environment` option to get the Twig_Environment instance in filters, functions, or tests; or explicitly implement Twig_Extension_InitRuntimeInterface if needed (not recommended).

https://github.com/phiamo/MopaBootstrapBundle/search?utf8=%E2%9C%93&q=initRuntime

**Comment by phiamo** [comment]
could you create a backward compatible PR?
