### ISSUE TITLE
Inline button groups need to be wrapped in an "input-group" on non-horizontal forms

### ISSUE THREAD

**Issue by lifo101** [phiamo/MopaBootstrapBundle#1127]
I use an inline button group to display a few radio boxes as a button group and with the default Mopa styles it won't render properly on non-horizontal forms. Horizontal forms are fine.

I override the `choice_widget_expanded` block with the following to fix it:

``` twig
{% block choice_widget_expanded %}
    {% spaceless %}
        {% if not horizontal %}
            <div class="input-group">
        {% endif %}

        {{ parent() }}

        {% if not horizontal %}
            </div>
        {% endif %}
    {% endspaceless %}
{% endblock %}
```

Before:
![before](https://cloud.githubusercontent.com/assets/367337/11249273/e266fe04-8df3-11e5-9c6d-a3201f27c7c6.png)
After:
![after](https://cloud.githubusercontent.com/assets/367337/11249272/e2664ac2-8df3-11e5-81f4-bd2714ddef59.png)

And in case you want to see it, this is how I build that form row:

``` php
$builder->add('type', 'entity', [
    'label' => 'Request Type',
    'class' => '...',
    'data_class' => '...',
    'expanded' => true,
    'widget_type' => 'inline-btn',
    'label_attr' => [ 'class' => 'btn-default' ],
    'horizontal_input_wrapper_class' => 'col-sm-4',
])
```

**Comment by phiamo** [comment]
Can you create a pr for this?
