### ISSUE TITLE
Duplicated form_errors in collections

### ISSUE THREAD

**Issue by grimmlink** [phiamo/MopaBootstrapBundle#1134]
Hi,

I have a collection form field with a count constraint on min = 1
Now, if I submit the form without adding to the collection, the error is duplicated:
![image](https://cloud.githubusercontent.com/assets/3241292/11398477/5b172f8a-9381-11e5-9e08-d0eb292f2dc1.png)

From what i saw in [fields.html.twig](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/Form/fields.html.twig), _form_row_ block calls 2 blocks:
- _form_message_ which contains
  `{{ form_errors(form) }}`
- _form_widget_compound_ which calls _form_rows_visible_ which contains

```
{% if errors|length > 0 %}
        <div class="symfony-form-errors">
            {{ form_errors(form) }}
        </div>
    {% endif %}
```

In which case removing the second call to errors would be a problem ?

**Comment by phiamo** [comment]
can you create a example for the sandbox to see this problem running?

**Comment by grimmlink** [comment]
Hi,

i can't install the sandbox

```
  Problem 1
    - The requested package knplabs/knp-menu-bundle could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for mopa/bootstrap-sandbox-bundle dev-master -> satisfiable by mopa/bootstrap-sandbox-bundle[dev-master].
    - mopa/bootstrap-sandbox-bundle dev-master requires knplabs/knp-menu-bundle 2.0.x-dev -> no matching package found.
```

my composer.json:

```
        "liip/theme-bundle": "dev-master",
        "knplabs/knp-menu-bundle": "2.0.x-dev",
        "mopa/bootstrap-sandbox-bundle": "dev-master"
```

**Comment by grimmlink** [comment]
@phiamo 

You can have a test with this: https://github.com/grimmlink/mopabs

it seems the error appears if error_bubbling => false` on the parent form

**Comment by vasakorol** [comment]
Hi,
I have same problem with sandbox:

`Problem 1
- Installation request for mopa/bootstrap-sandbox-bundle dev-master -> satisfiable by mopa/bootstrap-sandbox-bundle[dev-master].
- mopa/bootstrap-sandbox-bundle dev-master requires knplabs/knp-menu-bundle 2.0.x-dev -> no matching package found.`
Here is my composer

`"mopa/bootstrap-bundle": "dev-master",
"mopa/bootstrap-sandbox-bundle": "dev-master",
"twbs/bootstrap": "dev-master",`

**Comment by vasakorol** [comment]
`asd
as
da`

**Comment by Primo83** [comment]
Hi,
I have same problem,

Problem 1
    Installation request for mopa/bootstrap-sandbox-bundle dev-master -> satisfiable by mopa/bootstrap-sandbox-bundle[dev-master].
    mopa/bootstrap-sandbox-bundle dev-master requires knplabs/knp-menu-bundle 2.0.x-dev -> no matching package found.
