### ISSUE TITLE
Missing "spinning.less" file for font-awesome4

### ISSUE THREAD

**Issue by c1tru55** [phiamo/MopaBootstrapBundle#1139]
```
  [Less_Exception_Parser]                                   
  File `spinning.less` not found. in anonymous-file-0.less  
```

https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/public/less/font-awesome4/font-awesome.less#L14
https://github.com/phiamo/MopaBootstrapBundle/tree/master/Resources/public/less/font-awesome4

**Comment by bluntelk** [comment]
It was deliberately removed with commit 7a3b15c3b6b08b01b9075b0cefbfb018eca9f682

There is no reasoning in the commit message.

Can we please revert this commit

**Comment by bluntelk** [comment]
I have submitted a pull request that reverts that commit
https://github.com/phiamo/MopaBootstrapBundle/pull/1144

**Comment by bluntelk** [comment]
As a work around, instead of importing "mopabootstrapbundle-fa4" you can import "mopabootstrapbundle-fa" which is actually a newer version now of font awesome 4

**Comment by rpcjacobs** [comment]
+1

` [Assetic\Exception\FilterException]
  An error occurred while running:
  '/usr/bin/node' '/tmp/assetic_less41Sv4R'
  Error Output:
  FileError: 'spinning.less' wasn't found. Tried`

Caught my eye aswell just now, wrong folder has been upgraded. Should be reverted!
But does anyone actually use the regular verison!? Perhaps it has icons that are not available in fa4?

Maybe the regular version could be dropped and no font install neccessary anymore!

**Comment by mchojrin** [comment]
@bluntelk Where can you set such configuration?

**Comment by bluntelk** [comment]
@mchojrin if memory serves, you import it via your .less file in Resources/public/less/blah.less

It has been quite some time though since doing this
