### ISSUE TITLE
SASS: Incorrect relative path to bootstrap.scss

### ISSUE THREAD

**Issue by debach** [phiamo/MopaBootstrapBundle#1146]
Line 26 of `@MopaBootstrapBundle/Resources/public/sass/mopabootstrapbundle.scss` incorrectly is

    @import "../bootstrap-sass/assets/stylesheets/bootstrap/bootstrap";

but should be

    @import "../bootstrap-sass/assets/stylesheets/bootstrap";

Pull request #1147.

**Comment by phiamo** [comment]
use the 3.2 version

**Comment by debach** [comment]
Many thanks. I was unaware that this is a version issue and found nothing in the docs.

**Comment by debach** [comment]
Many thanks. I was unaware that this is a version issue and found nothing in the docs.

**Comment by MisatoTremor** [comment]
@debach Doc: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/usage/1-base-templates.md#templates
But maybe this should be also be written for SCSS in the Usage section below. :)

**Comment by phiamo** [comment]
Could you create a PR for this :-)

**Comment by MisatoTremor** [comment]
@phiamo OK ^^ What do you think about #1149

**Comment by phiamo** [comment]
@MisatoTremor perfect thanks
