### ISSUE TITLE
is there a Symfony3 integration ?

### ISSUE THREAD

**Issue by darkomenx** [phiamo/MopaBootstrapBundle#1148]
Hello,

I just want to know if your bundle run onto Symfony3 framework ?
If not you think that to plan this ?

Good works, good time and good luck !

**Comment by phiamo** [comment]
@TomasVotruba made a lot of improvements for sf 3.0 afaik it should work.

**Comment by rejsmont** [comment]
There are a few deprecation notices though. Like for example:
`Defining the getGlobals() method in the "initializr" extension without explicitly implementing Twig_Extension_GlobalsInterface is deprecated since version 1.23 for example`

**Comment by MisatoTremor** [comment]
@rejsmont That is a Twig deprecation notice and has nothing to do with Sf 3.0.

**Comment by phiamo** [comment]
but please feel free to create a bc compat PR
