### ISSUE TITLE
Can I remove class "form-control" only to one field in my form ?

### ISSUE THREAD

**Issue by Chrysweel** [phiamo/MopaBootstrapBundle#1150]
I have a form.

```
$builder
        ->add('my_field','choice',
                array(
                    'choices'=> $this->generateChoicesMatter($options['matters']),
                    'required'=>false,
                    'label' => "Escoge:",
                    'label_attr' => array('class'=>'col-sm-3 control-label'),
                    'multiple' => true
                )
            )
        ....
        );
    }
```

And in my template twig I have:
```
<div class="form-group">
			{{ form_label(form.matter) }}
			<div class="col-sm-7">
	        	{{ form_widget(form.matter) }}
	        	{{ form_errors(form.matter) }}
			</div>
		</div>
```

I want that field "my_field" has not class form-control, are there any solution ?

I use mopaBoostrapBundle version 3.0.0

thanks in advance

**Comment by Chrysweel** [comment]
I see that "form-control" is added here:

>https://github.com/phiamo/MopaBootstrapBundle/blob/master/Form/Extension/WidgetFormTypeExtension.php#L86

But I dont know how delete this option ...

Any suggestion please ? :)

**Comment by Chrysweel** [comment]
up ! 
can anyone help me?
:(

**Comment by isometriks** [comment]
```php
$builder
    ->add('name', 'text', array(
        'widget_form_control_class' => '',
    ))
;
```

I think should work? Your other option is to override the form theme for only that form element on the page.

**Comment by Chrysweel** [comment]
Ok @isometriks great! It work ! Thanks you very much !
