### ISSUE TITLE
Multiple add button for collection

### ISSUE THREAD

**Issue by BenoitLeveque** [phiamo/MopaBootstrapBundle#1152]
I'm trying to use multiple button to add new item inside a collection. each button has custom attribute that i would use to alter the row (default value)

do we have a way to find which button has cause the item to be added ?

**Comment by stephanvierkant** [comment]
I think you can change this code: https://github.com/phiamo/MopaBootstrapBundle/blob/5ee09c87f173c9be2eda9d50b4b3bd353e30ef91/Resources/public/js/mopabootstrap-collection.js#L207

Use `$btn` to get the class/id/data attributes/whatever from your button to alter the row.
