### ISSUE TITLE
How to properly use MopaBootstrap in a clean project

### ISSUE THREAD

**Issue by reypm** [phiamo/MopaBootstrapBundle#1153]
I am working in a Symfony 2.8 (does not know if MoopaBootstrap already support this release) project and I need to use Bootstrap so I decide to go with this bundle. After read the install docs I have a few doubts (and I think this could be added to the docs in order to be clear to new ones trying to use the bundle):

- I am not using LESS, I am not using SASS, should I install Bootstrap by hand? This means download the current Twitter Bootstrap release, copy each file to the bundle I am working on and including them using provided MopaBootstrap blocks? Is that right? 

I know there is a section where  says "do not ask" but I am not asking for help but for the right choice to make here after continue because my site looks ugly due to missing TB files.

**Comment by isometriks** [comment]
If you're using assetic you can just add bootstrap from one of the CDNs (it'll download it for you) or directly link to one. You could also place it in your `/public` folder and then reference it through `/bundles/app/css/bootstrap.min.css` etc. I use either the above way or in one using LESS customization I just downloaded it locally myself, the commands are just shortcuts, as long as the css makes it onto the page it doesn't matter how you do it.

**Comment by reypm** [comment]
@isometriks can you share your setup for using CDN? I know the common way by including from another bundle but this one with CDN sound interesting I just don't know how to config everything. Thx

**Comment by isometriks** [comment]
You can just do this:

```jinja
{% stylesheets 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %}
    <link rel="stylesheet" href="{{ asset(asset_url) }}">
{% endstylesheets %}
```

It will download that file locally for you. You'll have an issue with glyphicons unless you have the font file local as well so unless you're replacing it with fontawesome or something and including that too it may not always be the best. You also have to hope that it's available when you dump your assets as well.
