### ISSUE TITLE
The service "mopa_bootstrap.example.navbar" has a dependency on a non-existent parameter

### ISSUE THREAD

**Issue by patrickg15** [phiamo/MopaBootstrapBundle#1156]
Hello,
Please how could I solve this problem ?
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "mopa_bootstrap.example.navbar" has a dependency on a non-exist
  ent parameter "mopa_bootstrap.navbar.generic".

This happened after installation MopaBootstrapBundle and all the suggests bundle.

**Comment by jonny827** [comment]
Are you still having issue?  Have you followed the minimum instructions for the config.yml? If so, can you reinstall with the latest release and post if you have any more issues?

```
mopa_bootstrap:
    form: ~
    menu: ~  
```
