### ISSUE TITLE
glyphicons HTTP 404 - mopabootstrapbundle-3.2.scss

### ISSUE THREAD

**Issue by paljinov** [phiamo/MopaBootstrapBundle#1159]
I have the same issue as @nska02 in #1114.

The following line in file: **web\bundles\mopabootstrap\sass\mopabootstrapbundle-3.2.scss**

```
// variables
$icon-font-path: "/bundles/mopabootstrap/fonts/bootstrap/" !default;
```

is not working properly on the following platform:
**_CentOS Linux release 7.1.1503 (Core)
nginx version: nginx/1.6.3_**  

composer.json configuration

```
 "symfony/symfony": "^3.0",
 "mopa/bootstrap-bundle": "^3.0",
 "twbs/bootstrap-sass": "^3.3"...
```

Errors are:

> glyphicons-halflings-regular.ttf  GET 404
> glyphicons-halflings-regular.woff GET 404
> glyphicons-halflings-regular.woff2    GET 404 

![glyphicons_404](https://cloud.githubusercontent.com/assets/10164379/13265763/00f933c8-da75-11e5-8516-e3b07e856e5c.jpg)

If I include fonts by relative path everything is OK:

```
// variables
$icon-font-path: "../../../bundles/mopabootstrap/fonts/bootstrap/" !default;
```

Can this be solution ?

**Comment by deantomasevic** [comment]
Same error here, but with less.

```
"symfony/symfony": "3.2.*",
"twbs/bootstrap": "^3.3",
"twig/twig": "^1.0||^2.0",
"mopa/bootstrap-bundle": "^3.1",
```

![screenshot 2017-03-18 23 46 50](https://cloud.githubusercontent.com/assets/2656987/24076603/33a706b8-0c35-11e7-8344-6cd7a82fe1a0.png)

**Comment by deantomasevic** [comment]
Hi,

i found a solution: https://github.com/phiamo/MopaBootstrapBundle/issues/1114

Run:
`php bin/console mopa:bootstrap:install:font`
`php bin/console assetic:dump --env=dev`
`php bin/console cache:warmup --env=dev`

Everything is fine now.
