### ISSUE TITLE
Style form legend with class

### ISSUE THREAD

**Issue by Neodork** [phiamo/MopaBootstrapBundle#1161]
Hello there,

I am using MopaBootstrap in combination with Sonata Project. I'd like to edit the legend CSS to give it a color. This is simple by adding a class to the element.

I can provide a PR where the legend_class passes as default option if that is the desired solution.

``` twig

// Resources/views/Form/fields.html.twig

{% block form_legend %}
{% spaceless %}
    {% if label is empty %}
    {%- if label_format is defined and label_format is not empty -%}
        {% set label = label_format|replace({
        '%name%': name,
        '%id%': id,
        }) %}
    {%- else -%}
        {% set label = name|humanize %}
    {%- endif -%}
{% endif %}
    <{{ legend_tag }}  class="{{ legend_class }}">{{ label|trans({}, translation_domain) }}</{{ legend_tag }}>
{% endspaceless %}
{% endblock form_legend %}
```

**Comment by isometriks** [comment]
Sure, I think it can be added to: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Form/Extension/LegendFormTypeExtension.php quite easily. Not sure if we should make it more generic like `legend_attr` so people could add other things if they needed to. @phiamo  thoughts?

**Comment by phiamo** [comment]
i like the legend_attr idea! thnx a lot!

**Comment by Neodork** [comment]
:+1: I'll look into `legend_attr`

**Comment by Neodork** [comment]
Been a bit busy, still need it for some projects though so when I have time I will look into it. If anyone else feels like they need it right away feel free to create the PR.

**Comment by Neodork** [comment]
@isometriks So I looked into it I just couldn't find where to set the parameter (if actually required). If I set an array it goes to the remap function which is not what I want here. Any help would be appreciate
