### ISSUE TITLE
`HorizontalFormTypeExtension` doesn’t play well with `CollectionType` in latest Symfony stable

### ISSUE THREAD

**Issue by corphi** [phiamo/MopaBootstrapBundle#1167]
With symfony/symfony#18317 collection form prototypes have their parent set, but there is no inverse direction, i.e. the prototype is not part of the collection children.

`HorizontalFormTypeExtension` sets the `horizontal` view variable on root forms and bubbles its value to the form children. As prototypes are no longer root forms, their value stays `null` and evaluates to `false` in the [template](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/Form/fields.html.twig#L554).

**Comment by rejsmont** [comment]
Current workaround is to set `'horizontal' => true` for each child, though this is not clean and optimal solution. Also there is a duplicate issue #1176.

**Comment by MichaelMure** [comment]
Hi, I described my problem in Symfony's issues (https://github.com/symfony/symfony/issues/19355) and a dev suggested that it could be an usage error by MopaBootsrap (https://github.com/symfony/symfony/issues/19355#issuecomment-232362421)

Can someone experienced here have a look on the issue ?

**Comment by HeahDude** [comment]
Hi there, I confirm that a prototype should not be considered as a root form.

It used to work because of a kind of bug in the prototype creation from CollectionType, is there anyway you can fix it in your code? Thanks.

**Comment by isometriks** [comment]
@HeahDude can you try my PR?

https://github.com/phiamo/MopaBootstrapBundle/issues/1180

Check here to grab it if you don't know how: https://help.github.com/articles/checking-out-pull-requests-locally/

I just added a bunch more tests. I think it should be working properly now.

**Comment by HeahDude** [comment]
@isometriks thanks for taking care of this issue :)

Actually I don't use this lib, I was just saying that this "regression" is a bug fix on symfony side so it should be fix on "this" side. Thanks again, cheers!

**Comment by isometriks** [comment]
Ah ok, thanks!

**Comment by isometriks** [comment]
@corphi @rejsmont @MichaelMure I think I've solved this, try out v3.1.0 and let me know if you have better luck. You shouldn't have to set horizontal on all children anymore.

**Comment by MichaelMure** [comment]
It does work for me, thanks !
