### ISSUE TITLE
Badges in Menus

### ISSUE THREAD

**Issue by jonny827** [phiamo/MopaBootstrapBundle#1169]
@isometriks  @phiamo 

I would like to be able to have badges in my menus for example next to the [inbox icon] Inbox 42    where the 42 is a badge just like in the examples that shows how many unread messages a user has or it could be for number of Shopping Cart items, etc.

Current perceived options

1. Keep it part of the label such as (42) with "( )".
2. Remove the label except for the (42) and make the class="badges" on the Item.

Any more flexible options that allow the icon & label & badge on a menu item?

**Comment by isometriks** [comment]
We could add this to the menu extension as an option and alter the template, similar to how we do icons. Shouldn't be that hard.

**Comment by peshi** [comment]
@isometriks badge-class > badge_class in https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/extensions/2-navbars.md

**Comment by isometriks** [comment]
That one should be okay, I only change it when I set the extra. In the actual options it's a hyphen

**Comment by peshi** [comment]
Ah, my bad :)
👍
