### ISSUE TITLE
Integrate the basic Bootstrap 3 Symfony form theme

### ISSUE THREAD

**Issue by Soullivaneuh** [phiamo/MopaBootstrapBundle#1178]
This is out since 2.6: http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme

I think we should:
- Bump Symfony minimum requirement to 2.8+
- Use this theme to simplify the work on this bundle

What do you think?

**Comment by jonny827** [comment]
I like that idea.  When I had a moment I was going to open a PR in the sandbox repository as discussed in #1072 .  What does everyone else think?  @isometriks @phiamo

**Comment by phiamo** [comment]
Yeah go for it 😊

Am 12.08.2016 14:03 schrieb "jonny827" <notifications@github.com>:

**Comment by jonny827** [comment]
I have created an Issue to discuss this further. Please comment on it here [MopaBoostrap Documentation / Future of MopaBootStrap #47](https://github.com/phiamo/MopaBootstrapSandboxBundle/issues/47)
