### ISSUE TITLE
Undefined index: horizontal_label_div_class

### ISSUE THREAD

**Issue by Knagg0** [phiamo/MopaBootstrapBundle#1181]
After upgrading from 3.0.0 to 3.0.1 our tests fail:

Undefined index: horizontal_label_div_class
 ./vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Form/Extension/HorizontalFormTypeExtension.php:114
 ./vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:195
 ./vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:187
 ./vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:95
 ./vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:85
 ./vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:67
 ./vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:39

In our test we create a form using the factory.
Symfony version is 3.0.8... Do you need any further information?

**Comment by isometriks** [comment]
Have you made sure your cache is cleared? There is a container update which passes that array key into the form extension

**Comment by Knagg0** [comment]
Yes, i cleared the cache and also deleted the content of the cache directory to be sure.

**Comment by NyoCon** [comment]
same problem here, i changed version from "~3.0.0" to "3.0.0".

**Comment by cbeyer** [comment]
I had the same problem, after upgrading Symfony v2.7.15 => v2.7.16
During composer update :
- mopa/bootstrap-bundle dev-master (5f05310 => 95246ce)
- twbs/bootstrap dev-master (fb75e86 => 7e2741e)
It was resolved after cache clear.

**Comment by jonny827** [comment]
Are you still receiving errors? Are you able to upgrade to the latest Symfony in the 3.1.x branch ? Any further details if you are still having trouble would be helpful. Check the asset dump or proper Symlink has been setup, otherwise it may be a bug that exists in that branch of Symfony.   Provide more details or please close this Issue if you have resolved this already. Thank you.

**Comment by cbeyer** [comment]
I wrote : 

> It was resolved after cache clear

**Comment by jonny827** [comment]
@Knagg0  Were you able to resolve your issue? If, so please let us know the solution and close this Issue.  If not, please provide more details so that we may be able to assist you.

**Comment by damien-thiesson** [comment]
I have the same issue: Symfony 3.1.6, Map, and the 3.1.1 branch.

    use Mopa\Bundle\BootstrapBundle\Tests\Form\TypeTestCase;
    
    class TypeMessageTypeTest extends TypeTestCase
    {
        public function testSubmitValidData()
        {
            $form = $this->factory->create(TypeMessageType::class, new TypeMessage());
        }
    }

I have the following exception:

    1) Tests\FrontBundle\Form\Bo\Parametrage\TypeMessageTypeTest::testSubmitValidData                                                                                 
    Undefined index: horizontal_label_div_class                                                                                                                       
                                                                                                                                                                   
    D:\projets\p\vendor\symfony\phpunit-bridge\DeprecationErrorHandler.php:72                                                                        
    D:\projets\p\vendor\mopa\bootstrap-bundle\Mopa\Bundle\BootstrapBundle\Form\Extension\HorizontalFormTypeExtension.php:94                        [ h
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\ResolvedFormType.php:195                                                          
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\ResolvedFormType.php:187                                                          
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\ResolvedFormType.php:95                                                           
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php:85                                                                
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php:67                                                                
    D:\projets\p\vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php:39                                                                s
    D:\projets\p\tests\Presaje\FrontBundle\Form\Bo\Parametrage\TypeMessageTypeTest.php:22   

The form: 

    class TypeMessageType extends AbstractType
    {
        /**
         * @inheritdoc
         */
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            parent::buildForm($builder,$options);
            
            $helpBlock = "";
            /**
             * @var $type TypeMessage
             */
            $type = $options['data'];
            if(!empty($type->getAllowedVariables())){
                foreach (explode(',',$type->getAllowedVariables()) as $variable) {
                    if(in_array($variable, explode(',', $type->getRequiredVariables()))){
                        $helpBlock .= '&lt;strong&gt;%' .$variable . '%&lt;/strong&gt;, ';
                    } else {
                        $helpBlock .= '%' .$variable . '%, ';
                    }
                    
                }
            }
            $helpBlock .= '%signature%';
            
            $builder
                ->add('subject', TextType::class, [
                    'label'                     => $this->getTranslationPrefix().'subject.label',
                    'required'                  => true,
                    'render_required_asterisk'  => true,
                    'render_optional_text'      => false,
                    'attr'                      => [
                        'placeholder'   => $this->getTranslationPrefix().'subject.placeholder',
                        'title'         => $this->getTranslationPrefix().'subject.title',
                    ],
                ])
                ->add('is_available', ChoiceType::class, [
                    'label'                     => $this->getTranslationPrefix().'isCsnEnCopie.label',
                    'required'                  => true,
                    'render_required_asterisk'  => true,
                    'render_optional_text'      => false,
                    'expanded'                  => true,
                    'widget_type'  => 'inline',
                    'constraints' =>  new NotBlank(),
                    'attr'                      => [
                        'title'         => $this->getTranslationPrefix().'isCsnEnCopie.title',
                    ],
                    'choices'                      => [
                        'Oui'       => 1,
                        'Non'       => 0,
                    ],
                ])
                ->add('content', TextareaType::class, [
                    'label'                     => $this->getTranslationPrefix().'content.label',
                    'required'                  => true,
                    'render_required_asterisk'  => true,
                    'render_optional_text'      => false,
                    'label_render' => false,
                    'help_block'  => empty($helpBlock)?  '' :  "Paramètres possibles : "  . $helpBlock ,
                    'attr'                      => [
                        'placeholder'   => $this->getTranslationPrefix().'content.placeholder',
                        'title'         => $this->getTranslationPrefix().'content.title',
                        'class'         => 'notpreview',
                    ],
                ])
    
                ->add('buttons', FormActionsType::class, [
                    'buttons' => [
                        'check' => [
                            'type' => ButtonType::class, 'options' => [
                                'label' => $this->getTranslationPrefix().'check.label',
                                'attr'  => [
                                    'class' => 'btn-primary',
                                    'title' => $this->getTranslationPrefix().'check.title',
                                    'data-toggle' => 'modal',
                                    'data-target' => '#preview'
                                ],
                            ]
                        ],
                        'submit' => [
                            'type' => SubmitType::class, 'options' => [
                                'label' => $this->getTranslationPrefix().'submit.label',
                                'attr'  => [
                                    'class' => 'btn-primary hidden',
                                    'title' => $this->getTranslationPrefix().'submit.title',
                                ],
                            ]
                        ],
                    ],
                    'button_offset' => 'btn-row'
                ])
            ;
        }
    
        public function getName()
        {
            return 'p_front_bo_typemessage_form';
        }
    }

**Comment by stephanvierkant** [comment]
See #1179
