### ISSUE TITLE
Unknown "craue_addDynamicStepNavigationParameter" filter in "MopaBootstrapBundle:Form:formflow_stepList.html.twig" at line 7.

### ISSUE THREAD

**Issue by yupmin** [phiamo/MopaBootstrapBundle#1183]
craue_addDynamicStepNavigationParameter twig filter is not exists.

so. craue/formflow-bundle is required.

https://github.com/craue/CraueFormFlowBundle/blob/master/Twig/Extension/FormFlowExtension.php

**Comment by jonny827** [comment]
Yes, if you read the installation instructions for this bundle [here](https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/install/1-getting-started.md))  you would see that that bundle is part of the suggested composer bundles to take full advantage of the bundle.  Please close this Issue if this answers your question. Thank you.

**Comment by yupmin** [comment]
yes. i got it.

**Comment by jcrombez** [comment]
"part of the suggested" but triggers an error :/
