### ISSUE TITLE
Symfony 3 horizontal_wrap_children

### ISSUE THREAD

**Issue by cirovargas** [phiamo/MopaBootstrapBundle#1191]
Hi, im getting this error on some collection types (not all):

```
->add('files',CollectionType::class,array(
                'label' => 'app.dgpdependente.dgpDocumento',
                'translation_domain' => 'EntityTranslations',
                'entry_type' => DependenteDocumentoType::class,
                'allow_add' => true,
                'allow_delete' =>true,
                'widget_add_btn' => array(
                    'label' => 'Adicionar'
                ),
                'entry_options' => array(
                    'label' =>false,
                    'widget_remove_btn' => array(
                        'horizontal_wrapper_div' => array(
                            'class' => "col-md-2 m-t-25 text-right"
                        ),
                        'wrapper_div' => false,
                    ),
                    'widget_form_control_class' => 'row'
                ),
                'mapped' => false
            ))
```

> Key "horizontal_wrap_children" for array with keys "value, attr, form, id, name, full_name, disabled, label, label_format, multipart, block_prefixes, unique_block_prefix, translation_domain, cache_key, errors, valid, data, required, size, label_attr, compound, method, action, submitted, embed_form, static_text, help_block, help_label, help_label_tooltip, help_label_popover, help_block_tooltip, help_block_popover, help_widget_popover, render_fieldset, show_legend, show_child_legend, legend_tag, label_render, render_required_asterisk, render_optional_text, error_type, error_delay, widget_form_control_class, widget_form_group, widget_addon_prepend, widget_addon_append, widget_btn_prepend, widget_btn_append, widget_prefix, widget_suffix, widget_type, widget_items_attr, widget_form_group_attr, widget_checkbox_label, horizontal, horizontal_label_class, horizontal_label_offset_class, horizontal_input_wrapper_class, horizontal_label_div_class, omit_collection_item, widget_add_btn, widget_remove_btn, prototype_names, tabbed, allow_add, allow_delete, prototype"

Solved with a 'form.parent.vars.horizontal_wrap_children is defined' on fields.html.twig:550

`{% set show_horizontal_wrapper = horizontal and not (form.parent is not null and 'collection' in form.parent.vars.block_prefixes and form.parent.vars.horizontal_wrap_children is defined and form.parent.vars.horizontal_wrap_children is same as(false)) %}`

Anyone with the same problem?

**Comment by isometriks** [comment]
`horizontal_wrap_children` was removed. Have you copied the template or something from the repository? It's gone in 3.1 so that error shouldn't exist anymore. What version are you on?

**Comment by cirovargas** [comment]
Ive copied and make some changes on the base template, but this `horizontal_wrap_children` is on the bundle template

"symfony/symfony": "3.0.*",
"mopa/bootstrap-bundle": "^3.0",
