### ISSUE TITLE
Knp Menu translations on menu labels not supporting translation domain

### ISSUE THREAD

**Issue by toby-griffiths** [phiamo/MopaBootstrapBundle#1193]
Version affected: v3.1.0

I've just discovered that setting the translation domain on the menu items does not work in this bundle.

I've tracked this down to the `Mopa/Bundle/BootstrapBundle/Resources/views/Menu/menu.html.twig` template, which has the `label` block, which uses translations, but does not support the translation domain key as used in the `KnpMenuBundle::menu.html.twig` template.

As a quick solution I think extending the `KnpMenuBundle::menu.html.twig` template rather than the `menu.html.twig` one should do the trick.  I'll submit a PR for this now.

**Comment by phiamo** [comment]
Thanks a lot!

Mit freundlichen Grüßen
Philipp A. Mohrenweiser

You don't need to know everything,
you just need to know where to find it:
https://www.booksync.net
______________________________________

Mohrenweiser & Partner


Web: http://www.mohrenweiserpartner.de

2016-10-25 12:01 GMT+02:00 Toby Griffiths <notifications@github.com>:

**Comment by isometriks** [comment]
I looked through and it seems like there should be no BC issues here either, just allows you to set the translation domain if you want. This defaults to `messages` which is the same as not providing one at all.

**Comment by toby-griffiths** [comment]
Thanks for the quick acceptance of this.  Have an awesome day :o)
