### ISSUE TITLE
collection JS =>  .size()  change to .lenght

### ISSUE THREAD

**Issue by zigomario** [phiamo/MopaBootstrapBundle#1198]
collection.js is build with jquery 2.~
But with jquery 3.x , collection js is broken cause .size()  .( deprecated )

**Comment by stephanvierkant** [comment]
You're right: we should use .length() instead.

.size()
> version deprecated: 1.8, removed: 3.0
 https://api.jquery.com/size/

.length()

> version added: 1.0


https://api.jquery.com/length/
