### ISSUE TITLE
Twig2 Support

### ISSUE THREAD

**Issue by tacman** [phiamo/MopaBootstrapBundle#1204]
Twig2 is officially out.

http://twig.sensiolabs.org/doc/2.x/

Is it possible allow Twig 2 or Twig1 in Mopa?  Currently it's locked to Twig1.

**Comment by phiamo** [comment]
@tacman can you make a PR?

**Comment by tacman** [comment]
Looks like twig 2 requires PHP 7, my PR is failing.

https://travis-ci.org/phiamo/MopaBootstrapBundle

**Comment by Smart-Core** [comment]
Any ideas? :)

**Comment by isometriks** [comment]
It's passing now
