### ISSUE TITLE
Twig 2.x support

### ISSUE THREAD

**Issue by heddn** [phiamo/MopaBootstrapBundle#1208]
I'd like to re-open the discussion of adding Symfony 3.x support. I see #1148 was opened a year ago, but no real action performed yet. Perhaps this can get the ball rolling by planning out the steps necessary to make the code functional with Symfony 3.

**Comment by isometriks** [comment]
It should already be working on Symfony3? What are you having trouble with?

**Comment by heddn** [comment]
$  composer require mopa/bootstrap-bundle:~3 twbs/bootstrap:~3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mopa/bootstrap-bundle v3.0.0-beta2 requires symfony/symfony ~2.3-dev -> satisfiable by symfony/symfony[2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9] but these conflict with your requirements or minimum-stability.
    - mopa/bootstrap-bundle v3.0.0-beta1 requires symfony/symfony ~2.3-dev -> satisfiable by symfony/symfony[2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install mopa/bootstrap-bundle v3.1.1
    - Conclusion: don't install mopa/bootstrap-bundle v3.1.0
    - Conclusion: don't install mopa/bootstrap-bundle v3.0.1
    - Conclusion: don't install mopa/bootstrap-bundle v3.0.0
    - Conclusion: don't install mopa/bootstrap-bundle v3.0.0-RC2
    - Conclusion: don't install mopa/bootstrap-bundle v3.0.0-RC1
    - Conclusion: don't install mopa/bootstrap-bundle v3.0.0-beta4
    - Conclusion: remove symfony/symfony v3.2.2
    - Installation request for twig/twig (locked at v2.1.0) -> satisfiable by twig/twig[v2.1.0].
    - Installation request for mopa/bootstrap-bundle ~3 -> satisfiable by mopa/bootstrap-bundle[v3.0.0, v3.0.0-RC1, v3.0.0-RC2, v3.0.0-beta1, v3.0.0-beta2, v3.0.0-beta3, v3.0.0-beta4, v3.0.1, v3.1.0, v3.1.1].
    - Conclusion: don't install symfony/symfony v3.2.2
    - mopa/bootstrap-bundle v3.0.0-beta3 requires symfony/form ~2.3 -> satisfiable by symfony/form[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/form v2.3.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.14|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.15|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.16|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.17|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.18|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.19|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.20|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.21|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.22|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.23|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.24|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.25|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.26|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.27|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.28|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.29|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.30|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.31|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.32|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.33|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.34|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.35|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.36|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.37|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.38|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.39|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.40|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.41|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.42|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.3.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.0-BETA1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.0-BETA2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.0-RC1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.0-BETA1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.0-BETA2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.0-RC1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.0-BETA1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.0-BETA2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.0-BETA1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.0-BETA2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.14|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.15|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.16|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.17|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.18|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.19|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.20|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.21|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.22|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.23|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.0-BETA1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.14|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.15|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.16|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.9|don't install symfony/symfony v3.2.2
    - Installation request for symfony/symfony (locked at v3.2.2, required as ~3) -> satisfiable by symfony/symfony[v3.2.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by isometriks** [comment]
That's strage, works for me and installed Symfony 3.2

php composer.phar require mopa/bootstrap-bundle:~3.1 twbs/bootstrap:~3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 32 installs, 0 updates, 0 removals
  - Installing symfony/class-loader (v3.2.2) Downloading: 100%
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.2) Downloading: 100%
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.2) Downloading: 100%
  - Installing mopa/composer-bridge (v1.5.0) Loading from cache
  - Installing twig/twig (v1.31.0) Loading from cache
  - Installing symfony/inflector (v3.2.2) Downloading: 100%
  - Installing paragonie/random_compat (v2.0.4) Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0) Loading from cache
  - Installing symfony/property-access (v3.2.2) Downloading: 100%
  - Installing symfony/options-resolver (v3.2.2) Downloading: 100%
  - Installing symfony/intl (v3.2.2) Downloading: 100%
  - Installing symfony/polyfill-intl-icu (v1.3.0) Loading from cache
  - Installing symfony/event-dispatcher (v3.2.2) Downloading: 100%
  - Installing symfony/form (v3.2.2) Downloading: 100%
  - Installing symfony/twig-bridge (v3.2.2) Downloading: 100%
  - Installing symfony/http-foundation (v3.2.2) Downloading: 100%
  - Installing symfony/http-kernel (v3.2.2) Downloading: 100%
  - Installing symfony/filesystem (v3.2.2) Downloading: 100%
  - Installing symfony/config (v3.2.2) Downloading: 100%
  - Installing symfony/twig-bundle (v3.2.2) Downloading: 100%
  - Installing symfony/stopwatch (v3.2.2) Downloading: 100%
  - Installing symfony/routing (v3.2.2) Downloading: 100%
  - Installing symfony/finder (v3.2.2) Downloading: 100%
  - Installing symfony/dependency-injection (v3.2.2) Downloading: 100%
  - Installing psr/cache (1.0.1) Downloading: 100%
  - Installing symfony/cache (v3.2.2) Downloading: 100%
  - Installing doctrine/cache (v1.6.1) Loading from cache
  - Installing symfony/framework-bundle (v3.2.2) Downloading: 100%
  - Installing mopa/bootstrap-bundle (v3.1.1) Downloading: 100%
  - Installing twbs/bootstrap (v3.3.7) Downloading: 100%

**Comment by phiamo** [comment]
Could you propbably show your composer.json ?

Mit freundlichen Grüßen
Philipp A. Mohrenweiser

You don't need to know everything,
you just need to know where to find it:
https://www.booksync.net
______________________________________

Mohrenweiser & Partner


Web: http://www.mohrenweiserpartner.de

Craig Blanchette <notifications@github.com> schrieb am Fr., 3. Feb. 2017 um
20:24 Uhr:

**Comment by heddn** [comment]
"require": {
        "doctrine/doctrine-bundle": "~1",
        "doctrine/doctrine-cache-bundle": "~1",
        "doctrine/orm": "~2",
        "eightpoints/guzzle-bundle": "~5",
        "geerlingguy/drupal-vm": "~4",
        "guzzlehttp/guzzle": "~6",
        "incenteev/composer-parameter-handler": "~2",
        "knplabs/knp-menu-bundle": "~2",
        "knplabs/knp-paginator-bundle": "~2",
        "sensio/distribution-bundle": "~5",
        "sensio/framework-extra-bundle": "~3",
        "symfony/monolog-bundle": "~3",
        "symfony/polyfill-apcu": "~1",
        "symfony/swiftmailer-bundle": "~2",
        "symfony/symfony": "~3"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3",
        "symfony/phpunit-bridge": "~3",
        "phpunit/phpunit": "~5"
    },

**Comment by heddn** [comment]
I think the reason is I was using twig 2.x.I finally got it working, by dropping back to twig 1.x.

>     REASON: mopa/bootstrap-bundle v3.1.1 requires twig/twig ^1.14.2 -> satisfiable by twig/twig[v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0].

**Comment by isometriks** [comment]
I just merged allowing Twig 2 so this should be all set too, I'm going to add a new tag as well

**Comment by heddn** [comment]
Re-titling. I think that fixed things up nicely; composer liked it at least. Thanks for the fast support.

**Comment by isometriks** [comment]
:+1:
