### ISSUE TITLE
Potential BC break from new layout option

### ISSUE THREAD

**Issue by rossmotley** [phiamo/MopaBootstrapBundle#1219]
In #1044 a new `layout` option was introduced. This caused a breaking change for us because one of our form types was already setting a `layout` view variable in `\Symfony\Component\Form\FormTypeInterface::buildView`.

**Comment by isometriks** [comment]
Hmm. That is unfortunate that it collides like that. We probably could have / should have prefixed some of the options with `mopa_` but now I feel like it's more of a BC break to change them now. Realistically not many people are probably using it but in the case where somebody has extended the form templates it could cause a break for them. 

Can you just change your view variable to something else and fix it in your project? You can also still use `~3.1.0` as your composer restriction for this bundle as well. I don't believe there's really anything else important in 3.2 that you would need to upgrade for unless you want to use the new `layout` stuff?

**Comment by rossmotley** [comment]
@isometriks Perhaps adding a PHP notice/warning if there's a layout view variable already would be worth doing.

I guess it also would be good add a warning to the text at https://github.com/phiamo/MopaBootstrapBundle/releases/tag/v3.2.0 and perhaps https://github.com/phiamo/MopaBootstrapBundle/blob/master/CHANGELOG.md too.

For our project we've already resolved it by changing the names of our variables.
