### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by felipyamorim** [phiamo/MopaBootstrapBundle#1222]
Are there plans in the development roadmap to support bootstrap 4?

**Comment by tacman** [comment]
Symfony 3.4 now includes bootstrap 4 support:

https://symfony.com/blog/new-in-symfony-3-4-bootstrap-4-form-theme

**Comment by stephanvierkant** [comment]
I think we should use Symfony's form theme instead. See this discussion: https://github.com/phiamo/MopaBootstrapSandboxBundle/issues/47
