### ISSUE TITLE
Bundle dead?

### ISSUE THREAD

**Issue by deguif** [phiamo/MopaBootstrapBundle#1248]
It seems this bundle is dead.
There is no support for Symfony 5 and many deprecations triggered on Symfony 4.

Would it be possible to add some new maintainers to bring this bundle back to life?

**Comment by phiamo** [comment]
hi, if you have surplus feel free to create a pr!
I am not sure about isometriks time atm, but i could review it and then decide about new maintainers 😇

**Comment by deguif** [comment]
Hi @phiamo 

Thanks for your answer.
I'm going to propose several PRs to bring this bundle back to life.

Here's a starter: #1249

**Comment by phiamo** [comment]
Thanks a lot!

François-Xavier de Guillebon <notifications@github.com> schrieb am Do., 1.
Okt. 2020, 11:35:
