### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by phiamo** [phiamo/MopaBootstrapBundle#23]
Hi folks, do you have any idea how to ahieve unittesting the best way for this bundle?
i could of course do string comparison for input output, but i am atm not sure if thats a nice way.
Maybe it is cause markup shouldnt change, css might. 
But i would like to have some input.
Cheers Phil

**Comment by phiamo** [comment]
#956 introduced a new TypeTest i think for others relying on us thats a step forward we could and should probably add more tests for us, but i think thats not as urgent as other things

**Comment by isometriks** [comment]
Gonna close this. We still need more tests but at least we have some now!

https://github.com/phiamo/MopaBootstrapBundle/pull/1010

**Comment by phiamo** [comment]
yehaw !
