### ISSUE TITLE
Cannot import Javascripts

### ISSUE THREAD

**Issue by soerenmartius** [phiamo/MopaBootstrapBundle#238]
Hi, i am on latest sf2 and MopaBootstrapBundle.

The Javascript block like in the Example Template

{% javascripts filter='?yui_js' output='js/compiled/total.js'
    'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-transition.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-modal.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-dropdown.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-scrollspy.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-tab.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-tooltip.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-popover.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-alert.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-button.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-collapse.js'
    '@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-carousel.js'
    '@MopaBootstrapBundle/Resources/js/bootstrap-typeahead.js'
    '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-collection.js'
    '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-subnav.js'
%}

gives me an exception:

An exception has been thrown during the compilation of a template ("Unable to find file "@MopaBootstrapBundle/Resources/bootstrap/js/bootstrap-transition.js".") in "/Users/smartius/Sites/xaas/src/XAAS/CommonBundle/Resources/views/Default/index.html.twig".

**Comment by darkbluesun** [comment]
It is difficult to comprehend just how difficult you've made it to implement something as friendly and easy as Bootstrap.

**Comment by MisatoTremor** [comment]
@darkbluesun If you're talking about this bundle, please note that this issue is about 2 years old and there've been many improvements since then. ;)

**Comment by darkbluesun** [comment]
In searching for this particular error message,  this is all I found. I
could start a new issue in the main project if that works better.

**Comment by welsby** [comment]
Just hit the same issue, is there a nicer solution after the 2 years since the original suggestion?
The latest bootstrap (as per the install instructions) doesn't have a file called bootstrap-tooltip.js so I suspect it's more an instructional issue rather than the sym links
