### ISSUE TITLE
How to set a form legend ?

### ISSUE THREAD

**Issue by marmotz** [phiamo/MopaBootstrapBundle#275]
i saw a config to activate or not to show legend... but how set this name ?

**Comment by paul-mesnilgrente** [comment]
Hi everybody,

is there somebody who has found a "clean" solution to override this fieldset ? I like the idea of the fieldset. But there is no translation for this label in fosuser form type for the @phiamo solution. And in my opinion, the redefinition of the form type as @jcroll suggests is too complicated for this little point.

So is there a clean solution ?

Thanks.
