### ISSUE TITLE
The function "mopa_bootstrap_navbar" does not exist.

### ISSUE THREAD

**Issue by scr4tchy** [phiamo/MopaBootstrapBundle#589]
Hello,

I now have the beautiful error : 

The function "mopa_bootstrap_navbar" does not exist. Did you mean "mopa_bootstrap_menu" in HarmonyPageBundle:Default:layout.html.twig at line 51
500 Internal Server Error - Twig_Error_Syntax

Pretty cool as my bundle is well loaded, no error, builder created and ready from example. All has been checked twice. I used Controller Builder as suggested in your documentation. The command knp_menu_render and mopa_bootstrap_menu are working well.

And by the way, I've this in my config.yml
mopa_bootstrap:
    navbar:
         enabled: true

I also had, before :
mopa_bootstrap:
    navbar: ~

Best Regards.

**Comment by mchojrin** [comment]
@isometriks Your comment was exactly what I've been missing out on... thanks!
I spent a lot of time looking at my composer.json and AppKernel... Is that documented on the symfony site??

**Comment by isometriks** [comment]
@mchojrin it's just here in our documentation: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/extensions/2-navbars.md

The reason you have to enable it is because not everyone will be using knp menu bundle so it won't load services that doesn't exist.
