### ISSUE TITLE
How to include Bootstrap (for dummies)?

### ISSUE THREAD

**Issue by kiaplayer** [phiamo/MopaBootstrapBundle#59]
I've read documentation, but still don't understand how to include Bootstrap without LESS.
"Including as Submodule" and "Including automatically by composer" won't do for me, because it means some additional moves after project checkout and vendors update.
"Including as own vendor dependency in deps" get files, but how to use it?
I've tried "Including manually" but seems it does not work (assets:install does not copy files in web directory).

**Comment by Marinofull** [comment]
nice! It helped me :+1:
