### ISSUE TITLE
Finishing 3.0

### ISSUE THREAD

**Issue by isometriks** [phiamo/MopaBootstrapBundle#729]
Issue | Status | Assigned | Commit
---------|------------|--------------|----------
Make all files PSR-2 compatible | *Complete* | @sstok  | a370328
Update Form Collections Docs | *Complete* | @phiamo | f206207
Clean views/base_initializr.html.twig | *Complete* | @mweimerskirch | 25bcbed
`Twig\MenuExtension` creates a `MenuConverter` every time | Complete | @isometriks | 9c84983
bootstrap-collection.js License | Not Completed | (none) | (none)
Fix navbar-right issue | Completed | @isometriks | (none)
Replace glyphs with icon() | Completed | @isometriks | (none)

**Comment by phiamo** [comment]
@isometriks @peterrehm @bierdok @havvg @peshi @sstok @nysander @cordoval @allothers since this is a year ago, we should concentrate efforts helping craig getting #1000 and the new branches done. but can we close this issue?

**Comment by isometriks** [comment]
I think we can close this for now. We just need to clean up the documentation and merge a few PRs that are left.

**Comment by phiamo** [comment]
should we create a new issue referencing these thogether?

**Comment by isometriks** [comment]
Yeah, we could use the milestones are cordoval mentioned
