### ISSUE TITLE
add an element without any class

### ISSUE THREAD

**Issue by webspin** [phiamo/MopaBootstrapBundle#762]
Hi,

As far as i can see, all form elements get the 'form-control' class. Is there a way to avoid this, to get an element in the output without any class?

**Comment by Chrysweel** [comment]
Existe here: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Form/Extension/WidgetFormTypeExtension.php#L86

But @phiamo @webspin How can I modify it in my form ?
