### ISSUE TITLE
Breadcrumbs component

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#766]
I'm uncertain if people use breadcrumbs, but I think we should have one anyway :)

**Comment by phiamo** [comment]
ping @sstok

**Comment by sstok** [comment]
Integration should be very simple, the RollerworksNavigationBundle is only about the registering of menu's and breadcrumbs. But internally it uses the KNPMenuBundle for rendering.

**Comment by phiamo** [comment]
@sstok so do we need some doc or can we close this?

**Comment by sstok** [comment]
I think this can be closed :+1:

**Comment by phiamo** [comment]
Tnx
