### ISSUE TITLE
assetic:dump --watch fail

### ISSUE THREAD

**Issue by cesarve77** [phiamo/MopaBootstrapBundle#839]
Hello, Sorry for my poor english.

When make a assetic:dump all work fine a generate all my assets.

but if i use assetic:dump --watch give the follow error:
[error] An error occurred while running:
'/usr/local/bin/node' '/private/var/folders/28/wvch2c4n1rs06633p1r6rczr0000gp/T/assetic_less57DQvW'

Error Output:
NameError: variable @icon-font-path is undefined in glyphicons.less on line 13, column 8:
12   font-family: 'Glyphicons Halflings';
13   src: ~"url('@{icon-font-path}@{icon-font-name}.eot')";
14   src: ~"url('@{icon-font-path}@{icon-font-name}.eot?#iefix') format('embedded-opentype')",

I waste a lot of hour revolving this. Please help-

thanks

**Comment by LaRitournelle** [comment]
Same problem for me ...
I checked all my configuration,  I tried the trick but It doesn't work.
