### ISSUE TITLE
Assetic:dump crashing on @import "../../bootstrap-sass/lib/bootstrap.scss"

### ISSUE THREAD

**Issue by tetranz** [phiamo/MopaBootstrapBundle#843]
Sorry to rehash a issue similar to many that have come before but I seem to be stuck on this even after reading the previous issues. I've built a new dev machine with Ubunbu 13.10 but cannot get sass / compass working. It is working fine in the old machine. It's related to @import with a relative path.

I'm running with:
`"mopa/bootstrap-bundle": "2.2.0",
"twbs/bootstrap": "v2.3.2",
"jlong/sass-twitter-bootstrap": "dev-master",`

I haven't changed from 2.2.0 since https://github.com/phiamo/MopaBootstrapBundle/issues/542#issuecomment-24025881

My bootstrap-sass symlink is good. I do assets:install --symlink
web/bundles looks good. It includes a symlink to mopabootstrap.

My master layout includes:

`{% stylesheets
'bundles/mopabootstrap/sass/mopabootstrapbundle.scss'
<some of my own sass files>
filter='compass, cssrewrite, ?uglifycss' %}`

assetic:dump crashes at the line:
`@import "../../bootstrap-sass/lib/bootstrap.scss";`

with

`Output:
     error assetic_compasseoqKZO.scss (Line 23: File to import not found or unreadable: ../../bootstrap-sass/lib/bootstrap.scss.
  Load paths:
    /tmp
    /var/lib/gems/1.8/gems/compass-0.12.3/frameworks/blueprint/stylesheets
    /var/lib/gems/1.8/gems/compass-0.12.3/frameworks/compass/stylesheets
    /myAppPath/web/bundles/mopabootstrap/sass
    Compass::SpriteImporter)
     create assetic_compasseoqKZO.css`

If I go to the command line at web/bundles/mopabootstrap/sass I can see `../../bootstrap-sass/lib/bootstrap.scss`
with a simple `ls` or `more`.

It seems to be a problem of context, i.e., what directory is it really executing in or maybe not handling the nested symlink. I don't know enough about sass and compass to figure it out. I think I have the new machine setup the same as the old one. The only different I can see are the versions of sass and compass.

Old: Sass 3.2.1 (Media Mark) and Compass 0.12.2 (Alnilam)
New: Sass 3.3.3 (Maptastic Maple) and Compass 0.12.3 (Alnilam)

Thanks for any help.

**Comment by phiamo** [comment]
ping @henrypenny

**Comment by henrypenny** [comment]
Sorry for the late reply @phiamo I didn't actually change the project code for my work around, the compiler pass was added to my own bundle.
