### ISSUE TITLE
Wrong initial collection index

### ISSUE THREAD

**Issue by ro0NL** [phiamo/MopaBootstrapBundle#858]
Hi,

Im using the bootstrap collection JS asset for a symfony collection form field (which is mapped with a doctrine collection).

The collection is embedded with zero initial elements. When adding an element (the first) it gets index `1`. The initial index in the doctrine collection is `0`, this way validation errors etc. are not displayed at the correct field but at the 2nd collection field (as that one has index `1`) or on top of the form without a 2nd collection field.

When I debug the JS forcing to start index `0` everything works as expected. I changed:
`this.options.index[this.options.collection_id] = this.options.initial_size;`
to
`this.options.index[this.options.collection_id] = this.options.initial_size - 1;`

Can you have a look at this?

**Comment by phiamo** [comment]
@aferrandini @ro0NL @wolfwolker is there still anything to do here?

**Comment by wolfwolker** [comment]
Seems fixed in beta4

**Comment by phiamo** [comment]
So i close this
