### ISSUE TITLE
Overriding configuration on per-form basis

### ISSUE THREAD

**Issue by Misiur** [phiamo/MopaBootstrapBundle#859]
Hello there. The docs said that I have to do:

``` php
$builder
            ->setAttribute('horizontal_input_wrapper_class', 'col-lg-6')
```

But it doesn't seem to work. I looked at [sandbox form type](https://github.com/phiamo/MopaBootstrapSandboxBundle/blob/master/Form/Type/ExampleExtendedFormType.php), but adding options as form defaults doesn't work as well.

Am I missing something? Usually I just take a peek at unit tests, but well :(

**Comment by auipga** [comment]
is there a solution yet?

**Comment by isometriks** [comment]
That should be an option passed to the form, attributes are not for this.

```php
$builder
    ->add('name', 'text', array(
        'required' => true,
        'render_required_asterisk' => false,
    ))
;
```

**Comment by auipga** [comment]
Can't I set this to the form instead of each single field?

**Comment by Danita** [comment]
Please reopen this. I've been tearing my hair out for the past 2 hours and I can't still find a way to override the form options, neither from the builder nor from twig.

````twig
{{ form(my_form, { layout: 'horizontal' }) }} {# Doesn't work #}

**Comment by isometriks** [comment]
@Danita what is your form builder code? Passing in view options via twig unfortunately only affect the element you override because the form and options are already built. If you do it in the builder it should cascade to the other elements.

**Comment by Danita** [comment]
I managed to get it working with the builder. But I'm a frontender, and I come from BraincraftedBootstrapBundle, where this was possible directly from twig. Every option dealing with presentation was available from the template, where it should be. Now I have to ask the backend to modify things that belong to the frontend.

**Comment by isometriks** [comment]
Ok right, I'm very sorry you had a poor experience with the free software other people wrote for you to use that is barely maintained anymore due to Symfony having their own bootstrap templates.
