### ISSUE TITLE
Embedded forms

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#862]
Hi.

Is this supported?
http://symfony.com/doc/current/book/forms.html#embedding-a-single-object

I can't seem to align the embedded form correctly.

Example
```
        $builder->add('personal_profile', new PersonalProfileType(), array(
            'label' => 'Personal Profile',
            'label_render' => false,
            'required' => false,
            'horizontal_label_class' => 'col-md-2',
            'horizontal_input_wrapper_class' => 'col-md-4',
        ));
```

What did I miss?

**Comment by phiamo** [comment]
ping @peshi

**Comment by peshi** [comment]
@phiamo Have been away for a while, I'll look into it as soon as possible.

**Comment by phiamo** [comment]
i think this got merged :-)
