### ISSUE TITLE
form_rows_visible and errors

### ISSUE THREAD

**Issue by peshi** [phiamo/MopaBootstrapBundle#864]
Hi.

On every form this is generated even if there are no errors.

```
<div class="symfony-form-errors"></div>
```

From MopaBootstrapBundle:Form:fields.html.twig
```
{% block form_rows_visible %}
{% spaceless %}
    {% if form_errors(form) %}
        <div class="symfony-form-errors">
            {{ form_errors(form) }}
        </div>
    {% endif %}
    {% for child in form %}
        {% if 'hidden' not in child.vars.block_prefixes %} {# smbdy: why do we not add the hiddens of childs? 131024 phiamo: i think form rest should do this !? it was afaik removed because it cause side effekts #}
            {{ form_row(child) }}
        {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock form_rows_visible %}
```

How about:
```
    {% if not form.vars.valid %}
        <div class="symfony-form-errors">
            {{ form_errors(form) }}
        </div>
    {% endif %}
```

Anything preventing the usage of this condition instead of the current?

There's also a scenario and condition that should be added - when you use embedded forms described in https://github.com/phiamo/MopaBootstrapBundle/issues/862

It would render multiple 'symfony-form-errors' divs. 
```
<div class="symfony-form-errors"></div> (Main form)
<div class="form-group">....</div>
<div class="form-group">....</div>
<div class="form-group">....</div>
<div class="symfony-form-errors"></div> (Embedded form1)
<div class="form-group">....</div>
etc..
```

Thoughts regarding this issue are welcome.

**Comment by peshi** [comment]
@phiamo Have been away for a while, I'll look into it as soon as possible.

**Comment by phiamo** [comment]
https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/Form/fields.html.twig#L529 this got already fixed no?!
