### ISSUE TITLE
The filter "craue_addDynamicStepNavigationParameter" does not exist

### ISSUE THREAD

**Issue by stephanvierkant** [phiamo/MopaBootstrapBundle#883]
When clearing/warming up the cache, I found this error in my logs:

The template "MopaBootstrapBundle:Form:formflow_stepList.html.twig" contains an error: The filter "craue_addDynamicStepNavigationParameter" does not exist in "MopaBootstrapBundle:Form:formflow_stepList.html.twig" at line 7

I don't use any craue bundle. How can I prevent this error?

**Comment by kollegeJack** [comment]
I got the same error and the server refused to work on my production system. My solution was to add the following to my config.yml (only the *form* part)
```yaml
mopa_bootstrap:
    form: ~  # Adds twig form theme  support
```
That worked for me!
