### ISSUE TITLE
Problem with validation inside Tabs

### ISSUE THREAD

**Issue by Kezino** [phiamo/MopaBootstrapBundle#895]
Greetings!

I am using the bundle's form extensions in Silex. Everything seems to work perfectly, except for the validation of fields inside tabs. All errors are "bubbled" and bind to the main parent form. The field itself is always returns true for the $form->get('tab_name')->get('field_name)->isValid(); whereas $form->isValid() is false. I am totally stuck and will be very grateful for any help.

Best regards

**Comment by EvilKraft** [comment]
@Kezino Please help me. 
How have you integrated MopaBootstrapBundle with Silex?

**Comment by Kezino** [comment]
@EvilKraft Yes, I have created a Bridge to integrate it into Silex. Though, it was quite a long time ago, I cannot guarantee that the newest version will work with my bundle as expected.

**Comment by EvilKraft** [comment]
@Kezino Could you send me your code? May be I could modify it to use with new version.
I just want to add tabs on form. But I am novice in Silex and Symfony :(
