### ISSUE TITLE
access the collection items from a twig template

### ISSUE THREAD

**Issue by skypeter1** [phiamo/MopaBootstrapBundle#911]
I want to access to the individual items in a collection from a twig template. I've tried to do this in my form like i saw at the documentation about collections forms and is some like this:

{{form_start(form)}}
{{ form_row(form.name) }}

{%for collection in form.collection%}
{{ form_start(collection)}}
{{ form_row(collection.item) }}
{{ form_row(collection.otheritem) }}
{{ form_end(collection)}}
{%endfor%}

{{ form_end(form) }}

I need to render the fields of the collection in different columns and rows of a table. I've tried to do this but get no results. How can I do it?

**Comment by phiamo** [comment]
@daFish @skypeter1 #781 and #909 are closed / merged, does this prob still persist?

**Comment by daFish** [comment]
@phiamo Unfortunatly not. I'm currently wrestling with an implementation by overriding various blocks from the form theme to customize it for my needs. This is far from perfect and should only give me a first idea how it might by improved.
The issue @skypeter1 has also caught me and I'm trying to fix it. Not sure how this ends. At least I can show my collection in a table and add new rows to it.

**Comment by phiamo** [comment]
@skypeter1 if there is still help needed feeld free to reopen!
