### ISSUE TITLE
[DX] Improve Documentation

### ISSUE THREAD

**Issue by isometriks** [phiamo/MopaBootstrapBundle#921]
Some documentation is outdated, it is difficult to navigate, just generally needs to be reorganized.

**Comment by phiamo** [comment]
@isometriks @cordoval an we do something here atm?

**Comment by cordoval** [comment]
not that i know of @phiamo

**Comment by isometriks** [comment]
Gonna assign this to 3.0 release. We should move some of BC break listings and put them in the changelog and just link to it instead.

**Comment by LouTerrailloune** [comment]
I think a **link** to the home of the documentation (index.md) in the README.md will be very valuable. Currently there is only a mention of it and a direct link to the install part. 

Also, some pages are not linked from the index.md and some are not present in the bottom navigation (next / prev).

**Comment by phiamo** [comment]
@LouTerrailloune good proposal, could you take care of this and create a PR please

**Comment by LouTerrailloune** [comment]
Do you think we can remove configuration-reference.md ? user can run `app/console config:dump-reference mopa_bootstrap` to get it (and it will be up to date).

**Comment by phiamo** [comment]
if we put a big info about this somewhere on the top (e.g. index.md) i would prefer it that way yes!

**Comment by phiamo** [comment]
@LouTerrailloune could you add that snippet somewhere

**Comment by LouTerrailloune** [comment]
The snippet is in PR #1026 (with other thing)

[Page in the PR](https://github.com/LouTerrailloune/MopaBootstrapBundle/blob/93e948dd219d3add24394ad391528f0e8446b4f5/Resources/doc/index.md)

**Comment by phiamo** [comment]
so this can be closed ?

**Comment by isometriks** [comment]
Eh, not really. The documentation is still pretty poorly organized imo

**Comment by phiamo** [comment]
reading helps :-)

**Comment by LouTerrailloune** [comment]
@isometriks Are you talking about PR #1026 or current one ? What do you suggest ?

**Comment by LouTerrailloune** [comment]
@phiamo Don't close if the PR is not merged.

**Comment by isometriks** [comment]
Sorry, didn't notice that PR was dedicated to fixing the docs, but there's still a few random things here and there. The README.md has 2 places with BC breaks, it has the tabs section that just says "needs more info" just small things that need to be cleaned up or linked to. The further documentation part about MenuBuilder links to the sandbox where there is only a voter. Just needs some more love

**Comment by phiamo** [comment]
@isometriks this last comment was meant from me to me not you :) sure there is a lot more to do before we close this one ...

**Comment by isometriks** [comment]
@phiamo haha no problem, I didn't really take it that way anyway

**Comment by isometriks** [comment]
Closing in favor of - https://github.com/phiamo/MopaBootstrapBundle/issues/1072 with issue list.
