### ISSUE TITLE
datepicker broken after dev-master update (from beta3)

### ISSUE THREAD

**Issue by cellulosa** [phiamo/MopaBootstrapBundle#924]
This update broke our previous method of implementing the datepicker. Following the mopa/bootstrap documentation found [here](github.com/phiamo/MopaBootstrapBundle) we managed to get the datepicker html output, but the functionality of it is broken (the calendar cannot be closed and when a value is clicked, nothing is entered into the date input). No errors are generated within the console, does the documentation need updated to work with the current dev-master?

**Comment by phiamo** [comment]
ping @cellulosa
