### ISSUE TITLE
Missing bootstrap.css.map

### ISSUE THREAD

**Issue by 0x46616c6b** [phiamo/MopaBootstrapBundle#930]
At the moment the bundle does not give an map file for the `bootstrap.css`. This should provided because modern browser like Chrome/Chromium wants to load the map file if there is an map information in the css file. Now it returns a 404 by Symfony, which is not optimal. We can provide the file or comment out the include of the map file in the css file (see http://stackoverflow.com/a/24834942/1134277)

**Comment by phiamo** [comment]
ping @0x46616c6b

**Comment by 0x46616c6b** [comment]
Sorry for the inactivity. The simplest solution seems to copy the map file also in web/. Otherwise we must remove the include of the map file in the bootstrap.css and bootstrap.js.

**Comment by sgregoire** [comment]
You can use bootstrap.min.css to avoid this error.

**Comment by 0x46616c6b** [comment]
I see in newer versions the map file isn't the css files, so I can close that issue.
