### ISSUE TITLE
Add support for InstallFontCommand to composer post install script

### ISSUE THREAD

**Issue by mattsnowboard** [phiamo/MopaBootstrapBundle#941]
It would be nice to be able to run the install font command after doing a composer install/update.
I've switched workflows to use Vagrant so I'm frequently recreating a VM and just running composer update. The only command I have to run in addition is "php app/console mopa:bootstrap:install:font".

I could take a stab at a PR for this if I have time.

**Comment by phiamo** [comment]
ping @mattsnowboard
