### ISSUE TITLE
Break bundle into Library+Bundle

### ISSUE THREAD

**Issue by afurculita** [phiamo/MopaBootstrapBundle#953]
For projects that only use Symfony Components and not the FrameworkBundle, it will be very helpful to have a part of the MopaBootstrapBundle moved into a separate library, let's call it MopaBootstrap. In this case the bundle MopaBootstrapBundle will have only the mission to integrate the MopaBootstrap library into Symfony.

**Comment by phiamo** [comment]
@afurculita would you help us with this and start a PR?

**Comment by afurculita** [comment]
OK, @phiamo. One question: will we go with the directory structure suggested by @isometriks: src/Bundle and src/Component? Or another structure? What suggestions do you have?

**Comment by phiamo** [comment]
atm we use the Bundle namespace
so for component i would use Component namespace, more or less exactly what @isometriks described

**Comment by phiamo** [comment]
ping @afurculita :-)

**Comment by jonny827** [comment]
ping @afurculita   Would you like some help on this ?  

 I believe this would help have better separation of concerns and follow strong pattern from bundles that MopaBoostrapBundle expands upon such as KNPMenu/KNPMenuBundle.  Expanding the community brings more contributors to the project and allows developers the option to better focus on the interaction with Symfony through the bundle.

**Comment by jonny827** [comment]
I have begun an  Issue in the Sandbox Repository to discuss [MopaBoostrap Documentation / Future of MopaBootStrap #47](https://github.com/phiamo/MopaBootstrapSandboxBundle/issues/47) . Lets discuss refactoring there. @afurculita come join the discussion!
