### ISSUE TITLE
Remove form-control class for file input type

### ISSUE THREAD

**Issue by pradipchitrakar** [phiamo/MopaBootstrapBundle#955]
how to remove form-control class for file input type?
I have upload field which is rendered as 
&lt;input type=&quot;file&quot; class=&quot;form-control&quot; name=&quot;employment[file]&quot; id=&quot;employment_file&quot;&gt;

My form is :
->add('file', 'file', array(
                    'label' => 'Logo',
                    'required' => false
                ))

How to remove form-control class?

**Comment by Chrysweel** [comment]
+1 Hello @pradipchitrakar did you resolve it ?

I have a field in my form, which I dont want class form-control... :(
