### ISSUE TITLE
override variables bootstrap sass

### ISSUE THREAD

**Issue by xorgxx** [phiamo/MopaBootstrapBundle#962]
i try to integret bootstrap 3 sass in my project. and it since to be easy (i deed and it work well) !! with MopaBooTstrap, but i have one big probleme how can i override variables without changing in the Btw bundle??

i want to know if it is one easy way.

sorry for my bad speeling. :(
thank's for your help.

**Comment by senenh** [comment]
I'm trying to install the bundle with sass, but I'm getting the same error as xorgxx. After composer update I get:
`...\vendor\mopa\bootstrap-bundle\Mopa\Bundle\BootstrapBundle\Resources\public\bootstrap-sass exists and is no link!`
And if I do php app/console  mopa:bootstrap:symlink:sass , I get:
`Directory name must not be empty.`
Anyone?

**Comment by phiamo** [comment]
since i am not a sass user, i wont be abled to help at this time, try pinging some of the people excessivly improving the sass support of this bundle please!

**Comment by phiamo** [comment]
if there is still an issue, feel free to reopen!
