### ISSUE TITLE
[Feature] Wrap form label element in col-*, not being one 

### ISSUE THREAD

**Issue by stephanvierkant** [phiamo/MopaBootstrapBundle#976]
I would like to put a form label inside a column. Currenty a label element is a column, but content must be inside a column. Normally that isn't a big issue, except when you give the label a background color. 

Please take a look at the question on StackOverflow for more information: http://stackoverflow.com/questions/26994741/content-must-be-in-column-but-form-label-isnt

I think it must be possible to put labels inside a column instead of being a column.

**Comment by phiamo** [comment]
@stephanvierkant i wont have time to solve this in the near future if you want to create a PR feel free, also start it, and we can discuss and improve it further

**Comment by isometriks** [comment]
You should be able to accomplish this by overriding the form theme, I don't think this is something that needs to be added to the core and would add a lot of complicated and ugly if statements if we wanted to try something like this.

**Comment by stephanvierkant** [comment]
I finally added a Pull Request.

It wasn't that difficult, but because I was overriding the form theme, it hadn't a high priority for me. When I started a new project and encountered the same problem, I decided to fix this.
