### ISSUE TITLE
Folder 'Resources/public/bootstrap' missing?

### ISSUE THREAD

**Issue by matt-jay** [phiamo/MopaBootstrapBundle#981]
I am trying to follow the instructions here to use Bootstrap with the MopaBootstrapBundle, using Less: https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/2-base-templates.md

I created a file `myproject.less` in `MyNameSpace\MyBundle\Resources\public\less`. So far, it only contains

    @import "../../../../../../vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/less/mopabootstrapbundle-fa4.less";

Both in my IDE and when running `php app/console assetic:dump`, I am getting the following error:

    FileError: '../bootstrap/less/bootstrap.less' wasn't found in <path to my project>\vendor\mopa\bootstrap-bundle\Mopa\Bundle\BootstrapBundle\Resources\public\less\bootstrap-fontawesome4.less on line 22, column 1:

There is no folder `bootstrap`in that location. How would I supposed to be getting it set up there (couldn't find anything in the instruction). Am I missing a step?

Best
Matt

**Comment by phiamo** [comment]
related to #1000

**Comment by phiamo** [comment]
@matt-jay why did app/console mopa:bootstrap:symlink:less not work, what was the message, and what system are you using? win/mac/linux composer version php version etc?

**Comment by esqone** [comment]
Hi. I had a very similiar issue. The reason was wrong paths. I have fixed that by overriding bundle files. They might be usefull for you to implement that in next release:

[base_sass.html.twig | uploaded via ZenHub](https://files.zenhub.io/55a4e230bb283e44754ddd26)

[mopabootstrapbundle.scss | uploaded via ZenHub](https://files.zenhub.io/55a4e230bb283e44754ddd27)

**Comment by phiamo** [comment]
@esqone thanks a lot, we updated the command lately, hopefully this works now again ..

**Comment by alrayyes** [comment]
+1 Experiencing the same issue.

**Comment by alrayyes** [comment]
Upgrading to 3.0.0-beta4 seems to have fixed it
