### ISSUE TITLE
Wrong references to bootstrap JS in MopaBootstrapBundle::base_sass.html.twig

### ISSUE THREAD

**Issue by SecretR** [phiamo/MopaBootstrapBundle#984]
Currently `block foot_script_assetic` is linking to 
```
    '@MopaBootstrapBundle/Resources/public/bootstrap-sass/vendor/assets/javascripts/bootstrap/tooltip.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap-sass/vendor/assets/javascripts/bootstrap/*.js'
```

Path is wrong, correct one is (`vendor/` removed):
```
    '@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js'
    '@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/*.js'
```

**Comment by phiamo** [comment]
thats related to #1000

**Comment by isometriks** [comment]
Gonna resolve this with: https://github.com/phiamo/MopaBootstrapBundle/pull/1009

Please now extend https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/base_sass_3.2.html.twig (base_sass_3.2.html.twig)

Please create another issue if this does not work.
