### ISSUE TITLE
File to import not found or unreadable:

### ISSUE THREAD

**Issue by stevedeveloper1** [phiamo/MopaBootstrapBundle#985]
I hve this error wehn running php app/console assetic:dump

 [Assetic\Exception\FilterException]                                                                                                                                               
  An error occurred while running:                                                                                                                                                  
  '/usr/bin/ruby' '/usr/bin/sass' '--load-path' '/Users/steve_dev/Sites/work/imsl_bio/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass' '--scss' '--  
  cache-location' '/private/var/tmp' '/private/var/tmp/assetic_sassQPMozh'                                                                                                          
  Error Output:                                                                                                                                                                     
  Error: File to import not found or unreadable: ../bootstrap-sass/assets/stylesheets/bootstrap/bootstrap.                                                                          
         Load path: /Users/steve_dev/Sites/work/imsl_bio/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/sass                                             
          on line 26 of /private/var/tmp/assetic_sassQPMozh

**Comment by ivansf** [comment]
I can confirm this still happens with beta 4.

      "mopa/bootstrap-bundle": "v3.0.0-beta4",
      "twbs/bootstrap-sass": "~3.3.0"

I also had to change that line

**Comment by phiamo** [comment]
should we try not to link to any external library which has these frequent changes?

**Comment by MisatoTremor** [comment]
I think they did not know how to structure it at the beginning, but it seems stable now. So it should be OK now.

**Comment by phiamo** [comment]
so we could close this issue?

**Comment by philgagnon12** [comment]
I use **MopaBootstrapBundle/Resources/public/sass/mopabootstrapbundle-3.2.scss** which fixed the problem for me , I would say that , yes we can close this. Thanks !

**Comment by phiamo** [comment]
tnx
