### ISSUE TITLE
Wrong FilePaths for icons?

### ISSUE THREAD

**Issue by Nickolaus** [phiamo/MopaBootstrapBundle#989]
In:
mopabootstrapbundle.less, bootstrap-fontawesome.less and bootstrap-fontawesome4.less it seems that the path settings are incorrect, I got it working using:

bootsrap:
@icon-font-path: "../fonts/bootstrap/";

fa: 
@FontAwesomePath:   "../fonts/fa/";

fa4:
@FontAwesomePath:   "../fonts/fa4/";

**Comment by phiamo** [comment]
i think that could be related to #1000

**Comment by phiamo** [comment]
#936 was related o this to afai see ... @isometriks do we have any chance to get that configurable, or are we going to use bootstraps current paths?

**Comment by phiamo** [comment]
ping @isometriks

**Comment by phiamo** [comment]
is there any way to fix this generically? a new file or something?
