### ISSUE TITLE
mopa:bootstrap:install:font error when composer not local

### ISSUE THREAD

**Issue by Xigi** [phiamo/MopaBootstrapBundle#990]
I am using the homebrew version of composer and app/console mopa:bootstrap:install:font breaks with an error:

 [PharException]                                                                                                        
  internal corruption of phar "/usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer" (__HALT_COMPILER(); not found)  
         
Installing composer into the repo root is a good workaround for now.

**Comment by phiamo** [comment]
shouldnt be necessary, could you run the command with -v and check if thats related more to the https://github.com/phiamo/MopaComposerBridge than to bootstrap bundle then add a issue there and close this if its like that

**Comment by Xigi** [comment]
You are right, the exception trace shows it's about the composer bridge, closing this and opening it there.
