### ISSUE TITLE
Assectic error for the file path of tooltip.js

### ISSUE THREAD

**Issue by n1c01a5** [phiamo/MopaBootstrapBundle#995]
I got this error: ```assetic.ERROR: The template "MopaBootstrapBundle::base_sass.html.twig" contains an error: Unable to find file "@MopaBootstrapBundle/Resources/public/bootstrap-sass/vendor/assets/javascripts/bootstrap/tooltip.js"```

**Comment by phiamo** [comment]
i think this is also related to #1000

**Comment by isometriks** [comment]
Gonna resolve this with: https://github.com/phiamo/MopaBootstrapBundle/pull/1009

Please now extend https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/views/base_sass_3.2.html.twig (base_sass_3.2.html.twig)

Please create another issue if this does not work.
