### ISSUE TITLE
Assetic error with the template MopaBootstrapBundle:Form:formflow_stepList.html.twig

### ISSUE THREAD

**Issue by n1c01a5** [phiamo/MopaBootstrapBundle#996]
I got this error: ```assetic.ERROR: The template "MopaBootstrapBundle:Form:formflow_stepList.html.twig" contains an error: The filter "craue_addDynamicStepNavigationParameter" does not exist. Did you mean "craue_addDynamicStepNavigationParameters", "craue_removeDynamicStepNavigationParameters" in "MopaBootstrapBundle:Form:formflow_stepList.html.twig" at line 7```

**Comment by dafuer** [comment]
same problem.

Thanks

**Comment by phiamo** [comment]
is that related to https://github.com/phiamo/MopaBootstrapBundle/pull/998

**Comment by dafuer** [comment]
I think so. Now it is resolved for me. Thanks

**Comment by phiamo** [comment]
perfect
